# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

index:
  is_secure: false
  
configurator:
  is_secure: false
  
get_choose_style:
  is_secure: false
  
get_choose_app:
  is_secure: false
  
get_choose_email_signatures:
  is_secure: false
  
get_button:  
  is_secure: false
  
get_buttoncode:  
  is_secure: false  
  
get_static_code:  
  is_secure: false    