all:
  stylesheets:
  
indexSuccess:
  layout: layout
  components:
    content_top: [likebutton, description]
    content_sub: [likebutton, configurator]
    
webmastersSuccess:
  layout: layout_twocol
  components:
    content_sub: [likebutton, configurator_desc]
