# Production Environment
prod:
  mongodb:
    host:   donkeykong
    database_name:  'yiid'
    database_name_stats:  'yiid_stats'

  settings:
    url:              'http://yiid.it'
    host:             'yiid.it'
    widget_host:      'http://widgets.yiid.com'
    static:           'http://widgets.yiid.com'
    dev:              0

# Staging Environment
staging:
  mongodb:
    host:   donkeykong
    database_name:  'yiid_dev'
    database_name_stats:  'yiid_dev_stats'

  settings:
    url:              'http://stats.yiiddev.com'
    host:             'stats.yiiddev.com'
    widget_host:      'http://widgets.yiiddev.com'
    static:           'http://widgets.yiiddev.com'
    dev:              1

# Development Environment
dev:
  mongodb:
    host:   127.0.0.1
    database_name:  'yiid'
    database_name_stats:  'yiid_stats'

  settings:
    url:              'http://yiidstats.local'
    host:             'yiid.local'
    widget_host:      'http://widgets.yiid.local'
    static:           'http://widgets.yiid.local'
    dev:              1

# Test: Testing Environment
test:
  mongodb:
    host:   127.0.0.1
    database_name:  'yiid'
    database_name_stats:  'yiid_stats'

  settings:
    url:              'http://yiidstats.local'
    host:             'yiid.local'
    widget_host:      'http://widgets.yiid.local'
    static:           'http://widgets.yiid.local'
    dev:              0

# default values
all:
  sfForkedApply:
      applyForm: YiidApplyForm

  sfGuardPlugin:
    signinForm: NavigationLoginForm