<?php

/**
 * Coupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Coupon extends BaseCoupon {

  public function preInsert($event) {
    if($this->getDeal()->getCouponType()==DealTable::COUPON_TYPE_SINGLE) {
      if($this->getDeal()->getCouponQuantity()==DealTable::COUPON_QUANTITY_UNLIMITED) {
        $this->setCode('XyZaBc');
      }
    }
  }
}
