<?php

/**
 * Deal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yiid_stats
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Deal extends BaseDeal {

  public function addCoupons($params) {
    return $this->saveMultipleCoupons($params, true);
  }
  
  public function saveCoupons($params) {
    return $this->saveMultipleCoupons($params);
  }
  
  public function getRemainingCouponCount() {
    return $this->getCouponType()==DealTable::COUPON_TYPE_MULTIPLE ? $this->getCoupons()->count() : ($this->isUnlimited() ? 'unlimited' : $this->getCouponCurrentQuantity());
  }
  
  public function isUnlimited() {
    return $this->getCouponType()==DealTable::COUPON_TYPE_SINGLE &&
           $this->getCouponQuantity()==DealTable::COUPON_QUANTITY_UNLIMITED;
  }
  
  private function saveMultipleCoupons($params, $pIsAdding=false) {
    $codes = array();
    if($this->getCouponType()==DealTable::COUPON_TYPE_SINGLE) {
      if(!empty($params['single_code'])) {
        $codes[] = $params['single_code'];
      }
    } elseif($this->getCouponType()==DealTable::COUPON_TYPE_MULTIPLE) {
      // Convert line breaks to commas
      $couponString = preg_replace('/\n/', ',', $params['multiple_codes']);
      // Remove all remaining white space
      $couponString = preg_replace('/\s/', '', $couponString);
      $codes = explode(',', $couponString);
    }
    
    foreach ($codes as $code) {
      if(!empty($code)) {
        $c = new Coupon();
        $c->setCode($code);
        $c->setDeal($this);
        $c->save();        
      }
    }
    
   
    $count = $this->getCouponQuantity();

    if($pIsAdding && $this->getCouponType()==DealTable::COUPON_TYPE_SINGLE) {
      if(!$this->isUnlimited()) {
        $count += $params['quantity'];
      }
    } elseif($this->getCouponType()==DealTable::COUPON_TYPE_MULTIPLE) {
      $count += count($codes);
    }
    
    $this->setCouponQuantity($count);
    $this->save();

    
    return $this->getCouponQuantity();
  }

}
