<?php
/**
 * OauthRequestToken
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Matthias Pfefferle
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OauthRequestToken extends BaseOauthRequestToken {
  /**
   * morph the OauthRequestToken to an OAuthToken
   *
   * @author Matthias Pfefferle
   * @see OAuthToken
   * @return OAuthToken
   */
  public function toOAuthToken() {
    $lOAuthToken = new OAuthToken($this->getTokenKey(), $this->getTokenSecret());
    return $lOAuthToken;
  }
}
