<?php

/**
 * OnlineIdentity
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OnlineIdentity extends BaseOnlineIdentity
{

  protected $aPostApiClient = null;

  /**
   * builds the real profile-url using the identifier
   * @deprecated use $this->getProfileUri() now
   * @return string
   */
  public function getUrl() {
    return $this->getProfileUri();
  }

  public function getOAuthToken(){
  }

  public function getCommunity() {
    return CommunityTable::getInstance()->retrieveByPk($this->getCommunityId());
  }
}