<?php

/**
 * OnlineIdentity
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OnlineIdentity extends BaseOnlineIdentity
{

  /**
   * return User Objects who have added this OI
   */
  public function getConnectedUsers() {
    return UserIdentityConTable::getUsersConnectedToOnlineIdentity($this);
  }

  /**
   * returns IDs of Uyer Objects connected to that OI
   */
  public function getConnectedUserIds() {
    return UserIdentityConTable::getUserIdsConnectedToOnlineIdentity($this);
  }

  /**
   * builds the real profile-url using the identifier
   *
   * @return string
   */
  public function getUrl() {
    if ($this->getIdentityType() == OnlineIdentityTable::TYPE_IDENTITY) {
      return str_replace('%s', $this->getIdentifier(), $this->getCommunity()->getOiUrl());
    } else if ($this->getIdentityType() == OnlineIdentityTable::TYPE_URL) {
      return $this->getIdentifier();
    } else if ($this->getIdentityType() == OnlineIdentityTable::TYPE_IM) {
      return str_replace('%s', $this->getIdentifier(), $this->getCommunity()->getImUrl());
    } else {
      return null;
    }
  }
}
