<?php

/**
 * UserAvatar
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserAvatar extends BaseUserAvatar
{


  /**
   * runs after UserAvatar->save()
   *
   * @author Matthias Pfefferle
   * @param Doctrine_Event $pEvent
   */
  public function postSave($pEvent) {
    $this->getUser()->setDefaultAvatar($this->getAvatar());
  }


}
