<?php

/**
 * UserIdentityCon
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserIdentityCon extends BaseUserIdentityCon
{

  public function postInsert($event) {
    // the user adds a new OI to his account
    $lUser = $this->getUser();
    $lUser->updateOwnedIdentities(array($this->getOnlineIdentityId()));
  }
}
