<?php

/**
 * UserRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserRelation extends BaseUserRelation
{

   public function save(Doctrine_Connection $conn = null) {
    $lObjectToSave = $this->toArray(false);

    $lObjectToSave = UserRelationTable::saveObjectToMongoDb($lObjectToSave);
    $this->setId($lObjectToSave['_id']);
    if ($lObjectToSave) {
      return $lObjectToSave;
    }
    return false;

   }
}
