<?php

/**
 * YiidActivity
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class YiidActivity extends BaseYiidActivity
{

  /**
   *  saves are handled by the related Table-Class as we save them in MongoDB
   * (non-PHPdoc)
   * @see lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Doctrine_Record::save()
   */
  public function save(Doctrine_Connection $conn = null) {
    $lObjectToSave = $this->toArray(false);
    $lObjectToSave = YiidActivityTable::saveObjectToMongoDb($lObjectToSave);

    var_dump($lObjectToSave);die();
    $this->setId($lObjectToSave['_id'].""); // cast mongoID to string
    if ($lObjectToSave) {
      return $lObjectToSave;
    }
    return false;
  }

  public function delete(Doctrine_Connection $con = null) {
    $this->collection->remove(array("_id" => new MongoId($this->getId()) ));
  }


  public function migrateActivityObject($pIdentities, $pServices) {
    $this->setOiids($pIdentities);
    $this->setCids($pServices);
    $this->save();
  }
}
