<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid_stats
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function __toString() {
    return $this->getId().': '. $this->getEmailAddress();
  }

  public function getApiPaymentMethod() {
    $query = Doctrine_Query::create()
      ->from('PaymentMethod pm')
      ->where('pm.api_method = ?', 1)
      ->andWhere('pm.sf_guard_user_id = ?', $this->getId());

    return $query->fetchOne();
  }

  public function preSave($event) {
    if (!$this->getAccessToken()) {
      $this->setAccessToken(uniqid($this->getUsername()."_", true));
    }
  }


  public function hasApiMethod() {
    $lCount = Doctrine_Query::create()
      ->from('PaymentMethod pm')
      ->where('pm.sf_guard_user_id = ?', $this->getId())
      ->andWhere('pm.api_method = ?', true)
      ->count();

    if ($lCount > 0) {
      return true;
    } else {
      return false;
    }
  }
}