<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    yiid_stats
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function __toString() {
    return $this->getId().': '. $this->getEmailAddress();
  }

  public function getApiPaymentMethod() {
    $lQuery = Doctrine_Query::create()
      ->from('PaymentMethod pm')
      ->where('pm.primary_method = ?', 1)
      ->andWhere('pm.user_id = ?', $this->getId());

    return $query->fetchOne();
  }
}