# default values
all:
  sfForkedApply:
      applyForm: YiidApplyForm

  sfGuardPlugin:
    signinForm: NavigationLoginForm
  sfApplyPlugin:
    from:
      email: "noreply@yiid.com"
      fullname: "the yiid staff"
  sf_guard_plugin_success_signout_url: '@configurator'
  sf_guard_plugin_success_signin_url:  '@analytics_overview'