verify:
  url: /domain_profiles/verify
  param: { module: domain_profiles, action: verify }

domain_profiles:
  url: /domain_profiles/index  
  param: { module: domain_profiles, action: index }  

dashboard:
  url: /visit_history/index
  param: { module: visit_history, action: index }

update_language:
  url:   /updateLanguage/*
  param: { module: system, action: update_icon_language }

webmasters:
  url:   /webmasters
  param: { module: likebutton, action: webmasters }
  
like_get_code:
  url:   /likebutton/get_code
  param: { module: likebutton, action: get_code }

register:
  url: /register
  param: { module: auth, action: register }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_forgot_password:
  url:   /user/reset_request
  param: { module: sfApply, action: resetRequest }

sf_guard_register:
  url:   /user/new
  param: { module: sfApply, action: apply }
  
get_buttoncode:
  url:  /likebutton/get_buttoncode/*
  param: { module: likebutton, action: get_buttoncode}  
  
configurator:
  url:  /likebutton/index
  param: { module: likebutton, action: index}  
  
analytics:
  url:   visit_history/analytics
  param: { module: visit_history, action: analytics } 
  
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: likebutton, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
   
  


  