verify:
  url: /domain_profiles/verify
  param: { module: domain_profiles, action: verify }

domain_profiles:
  url: /domain_profiles/index
  param: { module: domain_profiles, action: index }

dashboard:
  url: /dashboard
  param: { module: dashboard, action: index }

update_language:
  url:   /updateLanguage/*
  param: { module: system, action: update_icon_language }

webmasters:
  url:   /webmasters
  param: { module: likebutton, action: webmasters }

register:
  url: /register
  param: { module: auth, action: register }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_forgot_password:
  url:   /user/reset_request
  param: { module: sfApply, action: resetRequest }

sf_guard_register:
  url:   /user/new
  param: { module: sfApply, action: apply }
  
sf_guard_settings:
  url:   /user/settings
  param: { module: sfApply, action: settings }

get_buttoncode:
  url:  /configurator/get_buttoncode/*
  param: { module: configurator, action: get_buttoncode}

configurator:
  url:  /configurator
  param: { module: configurator, action: index}

analytics_overview:
  url:   /analytics
  param: { module: analytics, action: index }

publisher_overview:
  url:   /publisher
  param: { module: publisher, action: index }

analytics:
  url:   /analytics/statistics
  param: { module: analytics, action: statistics }

domain_statistics:
  url:  /analytics/domain_statistics
  param:  { module: analytics, action: domain_statistics}

domain_detail:
  url:  /analytics/domain_detail
  param:  { module: analytics, action: domain_detail}

deal_analytics:
  url:  /deal_analytics/deal_statistics/*
  param:  { module: deal_analytics, action: deal_statistics}

deal_details:
  url:  /deal_analytics/deal_details/*
  param:  { module: deal_analytics, action: deal_details}

deal_analytics_index:
  url:  /deal_analytics/index
  param:  { module: deal_analytics, action: index}

select_period:
  url:  /analytics/select_period
  param:  { module: analytics, action: select_period}

get_analytics_content:
  url: /analytics/get_analytics_content
  param: { module: analytics, action: get_analytics_content }

deals:
  url:   /deals/campaign
  param: { module: deals, action: step_campaign }

dealapi:
  url:   /advertiser/dealapi
  param: { module: advertiser, action: apply_api }

advertiser:
  url:   /advertiser/index
  param: { module: advertiser, action: index }

publisher:
  url:   /publisher/index
  param: { module: publisher, action: index }
  
get_tags:
  url:   /deals/get_tags
  param: { module: deals, action: get_tags }  
  
get_tag_counts:
  url:   /deals/get_tag_counts
  param: { module: deals, action: get_tag_counts }  

get_create_index:
  url:   /deals/get_create_index
  param: { module: deals, action: get_create_index }

get_deal_table:
  url:   /deals/get_deal_table
  param: { module: deals, action: get_deal_table }

get_form_by_domain:
  url:   /deals/get_form_by_domain
  param: { module: deals, action: get_form_by_domain }

deal_save:
  url:   /deals/save
  param: { module: deals, action: save }

set_state:
  url:   /deals/set_state
  param: { module: deals, action: set_state }

edit_enddate:
  url:   /deals/edit_enddate
  param: { module: deals, action: edit_enddate }

get_create_form:
  url:  /deals/get_create_form
  param: { module: deals, action: get_create_form }

paste_codes:
  url:  /deals/paste_codes
  param: { module: deals, action: paste_codes }

save_codes:
  url:  /deals/save_codes
  param: { module: deals, action: save_codes }

save_quantity:
  url:  /deals/save_quantity
  param: { module: deals, action: save_quantity }

wellknown:
  url:  /.well-known/host-meta
  param: { module: discovery, action: hostmeta}

oexchange:
  url:  /discovery/oexchange
  param: { module: discovery, action: oexchange}

nodomain:
  url:  /system/nodomain
  param: { module: system, action: nodomain}

imprint:
  url:  /imprint
  param: { module: system, action: imprint}

subscribe_api:
  url: /subscribe
  param: { module: domain_profiles, action: subscribe_api}

pricing:
  url: /pricing
  param: { module: landing, action: pricing}

customer:
  url: /customer
  param: { module: landing, action: customer}

advertisements:
  url: /advertisement
  param: { module: advertisements, action: advertisement }

advertiser:
  url: /advertiser
  param: { module: advertiser, action: index}

publisher:
  url: /publisher
  param: { module: publisher, action: index}

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: landing, action: index }

default:
  url:   /:module/:action/*