<?php slot('content') ?>
  <h1>AGB</h1>

  <ul class="normal_list">
    <li>
      <h3>1. Allgemein</h3>
      <p>yiid ist ein Online-Dienst, der dir hilft, deine virtuellen Aktivitäten zu überschauen und dein virtuelles Kontaktnetzwerk zu organisieren. Der yiid-Dienst und das yiid-Netzwerk (zusammen „yiid“ oder „der Dienst“) werden von der</p>
      <p>ekaabo GmbH<br/>
		    Grundelbachstr. 84<br/>
		    69469 Weinheim<br/>
		    Telefon: +49 - 6201 - 845 20 0<br/>
		    Telefax: +49 - 6201 - 845 20 29<br/>
		    info { at } ekaabo { punkt } de<br/>
		    Geschäftsführer: Marco Ripanti<br/>
		    Eingetragen am Amtsgericht Mannheim unter HRB 701542
		  </p>
		  <p>und den zugehörigen Gesellschaften (zusammen „uns“, „wir“ oder „das Unternehmen“) betrieben. Durch den Zugriff auf oder die Nutzung unserer Webseite unter www.yiid.com oder der entsprechenden Handyversion
		    dessen (zusammen die „Seite“) oder durch das Posten einer Schaltfläche auf deiner Seite, erklärst du (der „Nutzer“), dass du unabhängig davon, ob du ein registriertes Mitglied von yiid bist,
		    diese Nutzungsbedingungen („Nutzungsbedingungen“ oder „Vereinbarung“) gelesen und verstanden hast und sie als verbindlich anerkennst. Wir behalten uns das Recht vor, nach eigenem Ermessen Teile dieser
		    Nutzungsbedingungen jederzeit und ohne weitere Benachrichtigung zu ändern, zu ergänzen oder zu löschen. In einem solchen Fall werden wir die an diesen Nutzungsbedingungen vorgenommenen
		    Änderungen auf dieser Seite veröffentlichen und oben auf der Seite das Datum der letzten Überarbeitung dieser Bedingungen vermerken. Wenn du nach einer solchen Änderung den Dienst bzw. die Seite weiterhin nutzt,
		    ist dies gleichbedeutend mit der Annahme der neuen Nutzungsbedingungen. Wenn du mit diesen oder zukünftigen Nutzungsbedingungen nicht einverstanden bist, darfst du den Dienst und die Seite weder aufrufen noch
		    nutzen (order weiterhin aufrufen oder nutzen). Du bist selbst dafür verantwortlich, die Seite regelmäßig dahingehend zu überprüfen, ob an diesen Nutzungsbedingungen Änderungen vorgenommen wurden, und dir solche
		    Änderungen gegebenenfalls durchzulesen.</p>
		  <p class="text_important">
		    BITTE LIES DIESE NUTZUNGSBEDINGUNGEN SORGFÄLTIG DURCH. SIE ENTHALTEN WICHTIGE INFORMATIONEN IN BEZUG AUF DEINE RECHTE, RECHTSMITTEL UND PFLICHTEN. DAZU GEHÖREN BESTIMMTE EINSCHRÄNKUNGEN
		    UND AUSSCHLÜSSE SOWIE EINE SCHLICHTUNGSKLAUSEL, IN DER GEREGELT IST, WIE STREITFÄLLE GELÖST WERDEN.
		  </p>
    </li>
    <li>
      <h3>2. Teilnahmeberechtigung</h3>
      <p>
        Eine Mitgliedschaft am Dienst ist nichtig, sofern sie verboten ist. Diese Seite ist ausschließlich für Nutzer vorgesehen, die mindestens dreizehn (13) Jahre alt sind, und für Nutzer der Seite unter 18, die sich derzeit an einer
        weiterführenden Schule oder im Studium befinden. Jede Registrierung für die Seite, jeder Zugriff auf die Seite und jede Nutzung der Seite durch Personen unter 13 oder durch Personen unter 18, die sich nicht an einer
        weiterführenden Schule oder im Studium befinden, wird als unbefugt sowie nicht gestattet betrachtet und gilt als Verstoß gegen diese Nutzungsbedingungen. Jede Nutzung des Dienstes oder der Seite gilt als Zusicherung,
        dass du mindestens 13 Jahre alt bist und dich an einer weiterführenden Schule oder im Studium befindest, oder aber, dass du mindestens 18 Jahre alt bist. Gleichzeitig versicherst du dadurch, dass du allen Bedingungen
        dieser Vereinbarung zustimmst und dich an diese halten wirst.
      </p>
    </li>
    <li>
      <h3>3. Registrierungsdaten; Kontosicherheit</h3>
      <p>In Erwägung deiner Nutzung der Seite stimmst du zu,</p>
      <ul class="normal_text">
        <li>richtige, aktuelle und vollständige Informationen über dich anzugeben, wie es von jeglichen Registrierungsformularen auf der Seite gefordert werden kann („Registrierungsdaten“);</li>
        <li>die Sicherheit deines Passworts und deiner Identität zu wahren;</li>
        <li>die Registrierungsdaten und alle anderen Informationen, die du dem Unternehmen gegenüber angibst, zu pflegen und umgehend zu aktualisieren, damit diese stets richtig, aktuell und vollständig sind; und</li>
        <li>die vollständige Verantwortung für jegliche Nutzung deines Kontos, und alle Aktionen, die während der Nutzung dieses vorgenommen werden, zu übernehmen.</li>
      </ul>
    </li>
    <li>
      <h3>4. Eigentumsrechte am Inhalt der Seite; eingeschränkte Lizenz</h3>
      <p>
        Alle Inhalte, die auf dieser Seite und über den Service verfügbar sind, einschließlich der Designs, Texte, Grafiken, Bilder, Videos, Informationen, Anwendungen, Software, Musik, Klänge und andere Dateien und deren Auswahl
        und Anordnung (die „Seiteninhalte“), sind urheberrechtlich geschütztes Eigentum des Unternehmens, dessen Benutzern oder Lizenznehmern und es werden alle Rechte vorbehalten. Seiteninhalte dürfen weder vollständig
        noch teilweise in irgendeiner Form oder auf irgendeine Art ohne die vorherige schriftliche Genehmigung des Unternehmens verändert, kopiert, verteilt, geframed, reproduziert, erneut veröffentlicht, heruntergeladen,
        gescrapt, angezeigt, gepostet, übertragen oder verkauft werden, mit der Ausnahme, dass das vorangehende nicht für deine eigenen Benutzerinhalte (wie unten definiert) gilt, die du auf rechtlich zulässige Weise auf der Seite veröffentlichst.<br/>
        Sofern es dir gestattet ist, die Webseite zu verwenden, wird dir eine eingeschränkte Lizenz gewährt, um auf die Seite zuzugreifen und die Seiteninhalte zu verwenden sowie eine Kopie eines Abschnitts daraus auszudrucken,
        auf die du ordnungsgemäß und einzig für deine persönliche, nicht-kommerzielle Nutzung zugegriffen hast, und unter der Voraussetzung, dass du alle Urheberrechts- und anderen Eigentumshinweise intakt lässt.
        Außer in deinen eigenen Benutzerinhalten darfst du keine Seiteninhalte auf irgendeine Internet-, Intranet- oder Extranet-Webseite hochladen oder dort neu veröffentlichen oder die Informationen in eine andere Datenbank
        oder Zusammenstellung integrieren. Jedwede andere Nutzung der Seiteninhalte ist strikt untersagt. Diese Lizenz unterliegt den vorliegenden Nutzungsbedingungen und erlaubt nicht die Nutzung von Datengewinnung, Robotern,
        Scraping- oder ähnlichen Datenerfassungs- oder Extraktionsmethoden. Jedwede Nutzung der Webseite oder der Seiteninhalte, mit Ausnahme der hiermit ausdrücklich erlaubten, ist ohne eine vorherige schriftliche Genehmigung
        des Unternehmens strikt untersagt und führt zur Aufhebung der hiermit gegebenen Lizenz. Eine derartige unerlaubte Nutzung kann auch geltende Gesetze verletzen, einschließlich Urheberrechte und Markenrechte und -gesetze
        und die geltenden Abkommen, Bestimmungen und Satzungen. Sofern nicht ausdrücklich hierin erwähnt, darf nichts in diesen Nutzungsbedingungen als Übertragung einer Lizenz an Rechten geistigen Eigentums gelten, sei es durch
        Rechtsverwirkung, stillschweigende Folgerung oder auf irgendeine andere Weise. Diese Lizenz kann jederzeit, ohne Vorankündigung und mit oder ohne Angabe von Gründen, entzogen werden.
      </p>
    </li>
    <li>
      <h3>5. Nutzerverhalten</h3>
      <p>
        Du hast verstanden, dass, mit Ausnahme der Werbeprogramme, die durch uns auf der Site angeboten werden, der Service und die Site ausschließlich für private, nicht kommerzielle Verwendung verfügbar sind.
        Du erklärst und sicherst zu, dass keinerlei Material, das über dein Konto übertragen wird oder auf andere Art durch dich im oder über den Service gepostet, übertragen oder freigegeben wird, die Rechte Dritter,
        wie zum Beispiel Urheberrechte, Markenrechte, das Recht auf Privatsphäre, Publizitätsrechte oder sonstige persönliche oder Eigentumsrechte, verletzt; oder verleumderisches, diffamierendes oder auf andere Art gesetzwidriges Material enthält.
      </p>
      <p class="text_important">Zusätzlich versicherst du, den Dienst oder die Seite nicht zu verwenden, um:</p>
      <ul class="normal_text">
        <li>E-Mail-Adressen oder sonstige Kontaktinformationen anderer Benutzer mit elektronischen oder sonstigen Mitteln vom Service oder von der Site zu erfassen oder zu sammeln, um nicht angeforderte E-Mails oder sonstige unerwünschte Mitteilungen zu verschicken;</li>
        <li>den Service oder die Site in gesetzwidriger oder sonstiger Art und Weise zu verwenden, die zu einer Beschädigung, Deaktivierung, Überlastung oder Beeinträchtigung der Site führen könnte;</li>
        <li>automatisierte Skripts zu verwenden, um Informationen vom Service oder von der Site zu sammeln oder auf andere Art und Weise mit dem Service oder der Site zu interagieren;</li>
        <li>Inhalte hochzuladen, zu posten, zu übertragen, freizugeben, zu speichern oder auf andere Art und Weise verfügbar zu machen, die wir als schädlich, bedrohlich, gesetzwidrig, diffamierend, verletzend, missbräuchlich, aufrührerisch, schikanierend, vulgär, obszön, betrügerisch, als Verletzung der Privatsphäre oder von Publizitätsrechten, als verabscheuenswürdig, rassistisch oder aus ethnischen oder sonstigen Gründen als anstößig betrachten;</li>
        <li>Videos hochzuladen, zu posten, zu übertragen, freizugeben, zu speichern oder auf andere Art und Weise verfügbar zu machen, die nicht persönlicher Natur sind und die nicht von dir oder deinen Freunden sind, von dir oder deinen Freunden aufgenommen wurden oder als Originalkunst oder -animation von dir oder deinen Freunden geschaffen wurden;</li>
        <li>sich für mehr als ein Benutzerkonto zu registrieren, sich im Namen einer anderen Person für ein Benutzerkonto zu registrieren oder sich im Namen einer Gruppe oder juristischen Person für ein Benutzerkonto zu registrieren;</li>
        <li>sich für eine andere natürliche oder juristische Person auszugeben oder falsche Angaben oder sonstige falsche Darstellungen über dich selbst, dein Alter oder dein Verhältnis zu einer anderen natürlichen oder juristischen Person zu treffen;</li>
        <li>nicht angefordertes oder nicht autorisiertes Material zum Zwecke der Werbung, der Einholung von Angeboten oder des Marketings, "Junk-Mails", "Spam", "Kettenbriefe", "Schneeballsysteme" oder jede sonstige Form der Einholung von Angeboten hochzuladen, zu posten, zu übertragen, freizugeben oder auf andere Art und Weise verfügbar zu machen;</li>
        <li>private Informationen Dritter, wie zum Beispiel Adressen, Telefonnummern, E-Mail-Adressen, Sozialversicherungsnummern und Kreditkartennummern, hochzuladen, zu posten, zu übertragen, freizugeben, zu speichern oder auf andere Art und Weise auf der Site öffentlich verfügbar zu machen;</li>
        <li>persönliche Informationen von Personen unter 18 zu erfragen oder Kennwörter oder Informationen, die der persönlichen Identifikation dienen, für kommerzielle oder gesetzwidrige Zwecke zu erfragen;</li>
        <li>Material hochzuladen, zu posten, zu übertragen, freizugeben oder auf andere Art und Weise verfügbar zu machen, das Softwareviren oder sonstigen Computercode, Dateien oder Programme enthält, die entwickelt wurden, um die Funktionsfähigkeit von Computersoftware oder -hardware oder Telekommunikationsgeräten zu stören, zu zerstören oder einzuschränken;</li>
        <li>eine andere Person einzuschüchtern oder zu schikanieren;</li>
        <li>Inhalte hochzuladen, zu posten, zu übertragen, freizugeben, zu speichern oder auf andere Art und Weise verfügbar zu machen, die eine Straftat darstellen, zu einer Straftat ermuntern oder Anweisungen für eine Straftat geben, die Rechte einer Partei verletzen, anderweitig eine Haftung begründen, oder einen Verstoß gegen geltendes nationales oder internationales Recht darstellen;</li>
        <li>das Konto, den Service oder das System einer anderen Person ohne Genehmigung des Unternehmens zu verwenden, eine falsche Identität für den Service oder die Site zu schaffen oder den Versuch einer solchen Handlung zu unternehmen.</li>
        <li>Inhalte hochzuladen, zu posten, zu übertragen, freizugeben, zu speichern oder auf andere Art und Weise verfügbar zu machen, die nach alleiniger Beurteilung durch das Unternehmen als anstößig betrachtet werden oder die eine andere Person teilweise oder vollständig an der Nutzung der Site hindern oder die das Unternehmen oder seine Benutzer in irgend einer Form einer Gefahr oder Haftung aussetzen könnten.</li>
      </ul>
    </li>
    <li>
      <h3>6. Auf der Seite gepostete Nutzerinhalte</h3>
      <p>
        Für alles, was du an Fotos, Profilen (einschließlich deinem Namen, deinem Image und deinem Aussehen), Nachrichten, Notizen, Text, Informationen, Musik, Videos, Anzeigen, Listen und sonstigen Inhalten an den Service oder auf die Site hochlädst oder dort veröffentlichst oder darstellst (im Folgenden als "Posten" bezeichnet) oder an andere Benutzer überträgst oder mit ihnen gemeinsam nutzt (zusammen der "Benutzerinhalt") bist allein du verantwortlich. Benutzerinhalt, den du nicht selbst erstellt hast oder für den du nicht die entsprechende Berechtigung besitzt, darfst du auf der Site oder im Service weder posten noch übertragen oder freigeben. Du hast verstanden und erklärst dich auch damit einverstanden, dass das Unternehmen berechtigt, aber nicht verpflichtet ist, die Site zu überprüfen und nach eigenem Ermessen, ohne Ankündigung und ohne Angabe von Gründen Inhalte der Site oder Benutzerinhalte zu löschen bzw. zu entfernen. Dies schließt Benutzerinhalte ein, die nach alleiniger Beurteilung durch das Unternehmen gegen diese Vereinbarung verstoßen oder die als anstößig oder illegal betrachtet werden könnten oder die die Rechte Dritter verletzen, Dritten schaden oder die Sicherheit Dritter bedrohen könnten. Für das Erstellen von Sicherungskopien und das Austauschen von Benutzerinhalten, die du auf der Site postest oder speicherst oder dem Unternehmen bereitstellst, bist du allein verantwortlich und trägst auch sämtliche in diesem Zusammenhang anfallenden Kosten und Auslagen.
      </p>
      <p>
        Mit dem Posten von Benutzerinhalt auf der Site gibst du uns sowohl die Genehmigung als auch die Anweisung, Kopien davon derart anzufertigen, wie wir es als notwendig erachten, um das Posten und Speichern des Benutzerinhalts zu erleichtern. Mit dem Posten von Benutzerinhalt auf einem beliebigen Teil der Site erteilst du dem Unternehmen automatisch eine unwiderrufliche, zeitlich unbegrenzte, nicht ausschließliche, übertragbare, vollständig bezahlte, weltweite Lizenz (mit dem Recht zur Vergabe von Unterlizenzen) für das Verwenden, Kopieren, öffentliche Aufführen, öffentliche Darstellen, Umformatieren, Übersetzen, Anfertigen von Auszügen (vollständig oder teilweise) und Weitergeben solcher Benutzerinhalte für kommerzielle, Werbe- oder sonstige Zwecke auf oder in Verbindung mit der Site oder mit dem Marketing für die Site, für das Erstellen abgeleiteter Werke oder die Einarbeitung solcher Benutzerinhalte in andere Werke und für das Vergeben und Autorisieren von Unterlizenzen zu Vorstehendem. Gleichzeitig sicherst du zu, dass du zur Erteilung dieser Lizenz berechtigt bist. Deinen eigenen Benutzerinhalt kannst du jederzeit von der Site entfernen. Wenn du deinen Benutzerinhalt entfernst, läuft die oben erteilte Lizenz zwar automatisch ab; du bestätigst jedoch, dass das Unternehmen archivierte Kopien deines Benutzerinhalts zurückbehalten darf. yiid  macht kein Eigentumsrecht an deinem Benutzerinhalt geltend; vielmehr bleibst du im Verhältnis zwischen uns und dir, unbeschadet der uns nach diesen Bedingungen eingeräumten Rechte, der alleinige Eigentümer deines gesamten Benutzerinhalts und jeglichen geistigen Eigentums und anderer Eigentumsrechte an deinem Benutzerinhalt.
      </p>
    </li>
    <li>
      <h3>7. yiid-Handydienste</h3>
      <p>Dieser Dienst beinhaltet verschiedene Angebote, die über dein Mobiltelefon verfügbar sind</p>
      <ul class="normal_text footer_list">
        <li>die Möglichkeit Inhalte auf yiid vom Mobiltelefon hochzuladen (Mobile Uploads),</li>
        <li>die Möglichkeit yiid-Nachrichten zu empfangen und zu beantworten und Pinnwandnachrichten zu schreiben mit Textnachrichten (Mobile Texte),</li>
        <li>die Möglichkeit yiid vom Mobiltelefon aus zu durchstöbern (Mobile Web)</li>
        <li>und die Möglichkeit einige yiid-Funktionen durch eine mobile Applikation die du heruntergeladen hast und auf deinem Mobiltelefon installiert hast (Mobile Client)</li>
      </ul>
      <p>Zusammen die "Mobilen Dienste". Es fallen Gebühren und Tarife des Mobilfunkanbieters für normale Nachrichten, Daten und andere Dienste an. Du solltest mit deinem Mobilfunkanbieter in Kontakt treten um herauszufinden welche Tarife verfügbar sind und was diese kosten. Zusätzlich kann das Herunterladen, Installieren und die Nutzung von manchen Mobilen Diensten von deinem Mobilfunkanbieter verboten oder eingeschränkt sein und nicht alle Mobile Dienste funktionieren mit allen Mobilfunkanbietern und mobilen Endgeräten. Deshalb solltest du mit deinem Mobilfunkanbieter abklären welche Mobilen Dienste auf deinem Mobilen Endgerät verfügbar sind und welche Einschränkungen, wenn überhaupt, bei der Verwendung der Mobilen Dienste vorhanden sind. Indem du die Mobilen Dienste benutzt stimmst du zu, dass wir mit dir durch SMS, MMS und Textnachrichten sowie anderen elektronischen Möglichkeiten auf deinem mobilen Endgerät bezüglich yiid in Kontakt treten und dass bestimmte Informationen über deine Nutzung der Mobilen Dienste an uns gesendet werden. In dem Moment in dem du deine Mobile Telefonnummer änderst oder deaktivierst, stimmst du zu, dass auch deine yiid Kontoinformationen umgehend aktualisierst um sicherzustellen, dass deine Nachrichten nicht an Personen gesendet werden, die deine alte Nummer erhalten.</p>
    </li>
    <li>
      <h3>8. Urheberrechtsbeschwerden</h3>
      <p>
        Wir respektieren die Rechte am geistigen Eigentum anderer und untersagen den Benutzern das Hochladen, Posten oder sonstige Übertragen von Material, das die Rechte am geistigen Eigentum Dritter verletzt, an die Website oder den Service von yiid. Wenn wir eine ordnungsgemäße Benachrichtigung über eine mutmaßliche Urheberrechtsverletzung erhalten, werden wir sofort das beanstandete Material entfernen oder den Zugang zu diesem Material sperren und die Konten von Wiederholungstätern laut Angabe in diesen Bestimmungen kündigen. Wenn du der Meinung bist, dass bestimmtes Material auf der Site ein Urheberrecht verletzt, das du besitzt oder kontrollierst, kannst du eine schriftliche Benachrichtigung über eine solche Urheberrechtsverletzung an unseren beauftragten Mitarbeiter schicken.
      </p>
    </li>
    <li>
      <h3>9. Webseiten und Inhalte Dritter</h3>
      <p>
        Die Site enthält (oder du erhältst über die Site oder den Service) Links zu weiteren Websites ("Sites Dritter") sowie Artikel, Fotos, Text, Grafiken, Bilder, Designs, Musik, Audio, Videos, Informationen, Anwendungen, Software und weitere Inhalte oder Objekte, die Dritten gehören oder von Dritten stammen (die "Anwendungen, Software oder Inhalte Dritter"). Solche Sites Dritter und Anwendungen, Software oder Inhalte Dritter werden von uns nicht auf Richtigkeit, Angemessenheit oder Vollständigkeit untersucht, überwacht oder geprüft. Weiterhin sind wir nicht für Sites Dritter, auf die über die Site zugegriffen wird, oder für Anwendungen, Software oder Inhalte Dritter, die auf der Site gepostet, über die Site zugänglich gemacht oder von der Site installiert werden, verantwortlich; dies erstreckt sich auf Inhalt, Richtigkeit, Anstößigkeit, Ansichten, Verlässlichkeit, Datenschutzpraktiken und sonstige Policies, die in den Sites Dritter oder in Anwendungen, Software oder Inhalten Dritter enthalten sind oder für sie gelten. Die Einbindung oder Verlinkung oder das Zulassen der Verwendung oder Installation einer Site Dritter oder von Anwendungen, Software oder Inhalten Dritter ist nicht gleichbedeutend mit einer diesbezüglichen Genehmigung oder Empfehlung von uns. Wenn du die Site verlässt und auf Sites Dritter zugreifst oder Anwendungen, Software oder Inhalte Dritter verwendest oder installierst, trägst du dafür das alleinige Risiko und solltest dir im Klaren darüber sein, dass unsere Bedingungen und Bestimmungen nicht mehr gelten. Du solltest dir auf jeder Site, auf die du von dieser Site aus gelangst, sowie für jede Anwendung, die du von der Site verwendest oder installierst, die jeweils geltenden Bedingungen und Bestimmungen, einschließlich bezogen auf Datenschutz und Praktiken der Datenerfassung, genau ansehen.
      </p>
    </li>
    <li>
      <h3>10. Teildienst</h3>
      <p>
        Das Unternehmen bietet eine Funktion an, mit der Nutzer der Seite Videos, Artikel und weitere Anwendungen Dritter, Software oder Inhalte von und/oder Links zu Seiten Dritter durch den Dienst mit anderen teilen oder in ihrem eigenen Mitgliederprofil posten können (der „Teildienst“). Du erkennst an und erklärst dich damit einverstanden, dass für deine Nutzung des Teildienstes und aller Links, Nutzerinhalte sowie Anwendungen, Software oder Inhalte Dritter, die durch den Teildienst geteilt werden, die oben dargelegten Regeln zum Nutzerverhalten und die sonstigen Bestimmungen und Bedingungen in den vorliegenden Nutzungsbedingungen gelten und vollständig eingehalten werden.
      </p>
    </li>
    <li>
      <h3>11. Verwendung von Teillinks durch Anbieter von Onlineinhalten</h3>
      <p>Entsprechend den Bestimmungen dieser Nutzungsbedingungen dürfen Sites Dritter, die die nachstehend beschriebenen Anforderungen erfüllen, auf Seiten ihrer Websites einen Freigabelink (Beschreibung siehe unten) in der durch das Unternehmen genehmigten Form platzieren, um die Verwendung des Freigabeservices zu erleichtern. Eine Site Dritter, die auf ihrer Website einen Freigabelink bereitstellt, wird hier als "Online-Content-Provider" bezeichnet und unterliegt den zutreffenden Abschnitten dieser Nutzungsbedingungen. Ein "Freigabelink" ist eine Schaltfläche und/oder ein Link in Textform auf einer Webseite eines Online-Content-Providers, der es uns nach dem Anklicken durch einen Benutzer ermöglicht, einen Freigabemechanismus zu starten, mit dessen Hilfe die Benutzer bestimmte Links und Inhalte von der betreffenden Seite mit anderen Benutzern gemeinsam nutzen oder in ihrem eigenen Mitgliedsprofil posten können.</p>
      <p>Falls es sich beim Freigabelink um eine Schaltfläche handelt, die Symbole oder sonstige grafische Abbildungen, Marken oder sonstige Materialien enthält, die im Eigentum des Unternehmens liegen, erhält der Online-Content-Provider die Berechtigung zur Verwendung dieser Abbildungen, Marken oder sonstigen Materialien zum ausschließlichen Zwecke des Platzierens des Freigabelinks auf der Site des Online-Content-Providers und ausschließlich in der durch das Unternehmen bereitgestellten Form. Falls es sich beim Freigabelink um einen Link in Textform handelt, muss der Link auf jeden Fall das Wort "yiid" enthalten. Die in diesem Absatz gewährten Rechte können durch das Unternehmen jederzeit nach eigenem Ermessen auch ohne die Angabe von Gründen widerrufen werden, und der Online-Content-Provider erklärt sich bereit, bei einer solchen Beendigung unverzüglich alle Freigabelinks von seiner Site zu entfernen.</p>
      <p>Damit ein Online-Content-Provider auf seinen Seiten einen Freigabelink bereitstellen kann, darf die betreffende Site Dritter keine Webinhalte enthalten, die nach ihrem Freigeben oder Posten durch einen Benutzer eine Verletzung der oben dargelegten Regeln zum Benutzerverhalten darstellen würden. Ohne Einschränkung der obigen Bestimmungen sichert der Online-Content-Provider zu, keinen Freigabelink auf einer solchen Website zu posten, die Inhalte enthält, die verletzend, schädlich, bedrohlich, gesetzwidrig, diffamierend, missbräuchlich, aufrührerisch, schikanierend, vulgär, obszön, anzüglich, betrügerisch, eine Verletzung der Privatsphäre oder von Publizitätsrechten sind oder die das Unternehmen oder seine Benutzer in irgend einer Form einer Gefahr oder Haftung aussetzen könnten. Außerdem sichert der Online-Content-Provider zu, dass eine solche Website weder gegenwärtig noch zukünftig derartige Inhalte enthält. Mit der Bereitstellung eines Freigabelinks erklärt sich der Online-Content-Provider damit einverstanden, das Unternehmen, dessen Tochtergesellschaften und verbundene Unternehmen und Mitglieder des Aufsichtsrates/Vorstandes, leitende Angestellten, Vertreter, Auftragnehmer, Partner und Arbeitnehmer schadlos zu halten und freizustellen von jeglichem Verlust, Haftung, Ansprüchen, Forderungen, Schäden, Kosten und Auslagen, einschließlich angemessener Anwaltsgebühren, die im Zusammenhang mit einem solchen Freigabelink, sonstigen Links, Inhalten oder anderen Objekten oder Materialien, die über einen solchen Freigabelink freigegeben oder bereitgestellt werden können, entstehen, oder im Zusammenhang eines Verstoßes oder mutmaßlichen Verstoßes gegen die vorangegangenen Garantien und Zusicherungen. </p>
      <p>Mit der Bereitstellung eines Freigabelinks erteilt der Online-Content-Provider dem Unternehmen automatisch eine unwiderrufliche, zeitlich unbegrenzte, nicht ausschließliche, übertragbare, vollständig bezahlte, weltweite Lizenz (mit dem Recht zur Vergabe von Unterlizenzen) zur Nutzung des Freigabeservices für das Verlinken, Verwenden, Kopieren, Veröffentlichen, Streaming, öffentliche Aufführen, öffentliche Darstellen, Umformatieren, Übersetzen, Erstellen von Auszügen (vollständig oder teilweise), Zusammenfassen und Weitergeben der Inhalte, Links und sonstigen Materialien beliebiger Art, die sich auf Webseiten befinden, auf denen der Online-Content-Provider den Freigabelink platziert. Gleichzeitig sichert der Online-Content-Provider zu, dass er zur Erteilung dieser Lizenz berechtigt ist. </p>
    </li>
    <li>
      <h3>12. yiid-Plattformanwendungen</h3>
      <p>Die yiid-Plattform besteht aus von yiid  bereitgestellten Anwendungsprogrammierschnittstellen (APIs) und Services, die es fremdem Entwicklern ("Plattformentwicklern") ermöglichen, Websites und Anwendungen zu erstellen, mit deren Hilfe Daten, die durch yiid und dessen Benutzer zur Verfügung gestellt wurden, und/oder autorisierte Daten von Sites Dritter abzurufen, um sie auf der yiid-Site zu verwenden ("Plattformanwendungen")</p>
      <p>Plattformentwickler dürfen die yiid-Plattform nur verwenden und Plattformanwendungen nur erstellen in Übereinstimmung mit den Bedingungen einer Vereinbarung, die zwischen yiid und dem jeweiligen Plattformentwickler abgeschlossen wurde ("Bedingungen für Entwickler"). Unsere Standardbedingungen für Entwickler bestehen aus den Allgemeine Geschäftsbedingungen für yiid-Entwickler und den zugehörigen Richtlinien für yiid-Plattformanwendungen. Von Zeit zu Zeit schließen wir separate Vereinbarungen mit bestimmten außen stehenden (fremden) Plattformentwicklern ab, die abweichende oder zusätzliche Bedingungen enthalten. Voraussetzung dafür ist, dass jede solche separate Vereinbarung den betreffenden Plattformentwickler darauf verpflichtet, deine Informationen ausschließlich gemäß deinen Einstellung der Privatsphäre auf yiid anzuzeigen. Die Standardbedingungen für Entwickler können durch das Unternehmen jederzeit nach eigenem Ermessen und ohne vorherige Ankündigung geändert werden. Deshalb solltest du diese Dokumente von Zeit zu Zeit genau ansehen.</p>
      <p>Benutzer, die Plattformanwendungen installieren, müssen den Bedingungen in den Nutzungsbedingungen für Plattformanwendungen ("Nutzungsbedingungen für Anwendungen") und in diesen Nutzungsbedingungen zustimmen. Die Nutzungsbedingungen für Anwendungen können durch das Unternehmen jederzeit nach eigenem Ermessen und ohne vorherige Ankündigung geändert werden. Deshalb solltest du dir diese Bedingungen von Zeit zu Zeit und bei jeder Installation einer Anwendung genau ansehen. Plattformentwickler können von dir als Bedingung für eine Verwendung von Plattformanwendungen fordern, dass du deren eigene Allgemeine Geschäftsbedingungen, Datenschutz-Policies und/oder weiteren Policies akzeptieren musst. Plattformanwendungen werden durch yiid  nicht bestätigt, unterstützt oder geprüft. Wir sind für deine Nutzung oder die Unmöglichkeit der Nutzung einer Plattformanwendung nicht verantwortlich; dies erstreckt sich auch auf Inhalt, Richtigkeit und Verlässlichkeit solcher Anwendungen und auf die Datenschutzpraktiken und sonstigen Bestimmungen der Entwickler. </p>
      <p>Wenn du, deine Freunde oder Mitglieder deines Netzwerks Plattformanwendungen verwenden, können solche Plattformanwendungen gemäß der Einstellung der Privatsphäre, die in unseren Datenschutzrichtlinien genauer beschrieben wird, auf bestimmte Informationen über dich zugreifen und sie mit anderen gemeinsam nutzen. Die Plattformentwickler müssen bestimmten Einschränkungen bezüglich des Zugriffs auf solche Informationen sowie deren Speicherung und Verwendung zustimmen. Obwohl wir Maßnahmen vertraglicher und technischer Art ergriffen haben, um den möglichen Missbrauch solcher Informationen durch Plattformentwickler zu begrenzen, können wir, da wir diese Entwickler nicht überwachen und prüfen, nicht garantieren, dass sich alle Plattformentwickler auch an diese Einschränkungen und Vereinbarungen halten werden. Bestimmte Aktionen, die du über die Plattformanwendungen ausführst, können deinen Freunden in deinem Profil, im Mini Feed und im News Feed angezeigt werden, und du kannst auf der Seite für die Einstellung der Privatsphäre dafür sorgen, dass deine über die Plattformanwendungen ausgeführten Aktionen nicht mehr angezeigt werden. Wenn du einen Missbrauch von Informationen über die yiid-Plattform vermutest, dann melde dies unverzüglich. Hinweise dazu findest du in unseren Datenschutzrichtlinien. </p>
    </li>
    <li>
      <h3>13. yiid-XChange</h3>
      <p>yiid-XChange („XChange“) ermöglicht den teilnehmenden Webseiten von Drittanbietern genauso wie yiid-Plattform-Anwendungen zu funktionieren. Erlaubst du der Webseite eines Drittanbieters mit yiid in Verbindung zu treten, so kannst du deine Anmeldeinformationen für yiid  verwenden, um dich auf dieser Webseite anzumelden. Die Webseite des Drittanbieters kann dann: Neuigkeiten-Meldungen sowie andere Meldungen über Maßnahmen, die du auf der Webseite durchführst, erstellen und veröffentlichen; auf mit dir zusammenhängenden yiid-Informationen zugreifen (einschließlich deiner Profilinformationen, Freunde und Privatsphäre-Einstellungen), damit du deine yiid-Informationen auf der Seite des Drittanbieters verwenden kannst; sowie die Interaktion mit deinen Freunden auf der Webseite ermöglichen. Um XChange verwenden zu können, musst du zustimmen, dass yiid deine yiid-Cookies überprüfen darf, wenn du teilnehmende Webseiten Dritter besuchst, sowie Informationen über die Maßnahmen, die du auf diesen anderen Webseiten durchführst, erhalten darf. Wenn du einer teilnehmenden Webseite von Drittanbietern erlaubst mit yiid in Verbindung zu treten, stimmst du zudem zu, dass yiid  und diese Webseiten Neuigkeiten-Meldungen sowie Meldungen über Aktionen, die du auf der Webseite durchführst, ohne zusätzliche Genehmigungen erstellen und veröffentlichen.</p>
      <p>Wenn deine Freunde ihre yiid-Kontos mit einer Webseite eines teilnehmenden Drittanbieters verbinden, dann ermöglicht yiid-XChange diesen ihre Yiid-Freunde, die ebenfalls Nutzer dieser Webseite Dritter sind, zu finden und zu Connect einzuladen. Falls du nicht möchtest, dass dich deine Freunde dazu einladen können, ändere deine Privatsphäre-Einstellungen, um diese Funktion zu sperren.</p>
      <p>XChange ermöglicht dir zudem yiid und Webseiten von teilnehmenden Drittanbietern zu erlauben, Neuigkeiten-Meldungen sowie andere Meldungen über Maßnahmen, die du auf solchen Webseiten ergriffen hast, zu erstellen und zu veröffentlichen. Dies ist auch dann der Fall, wenn du den XChange-Prozess nicht durchlaufen hast. In diesen Fällen wirst du gefragt, ob du die Meldung auf yiid veröffentlichen.</p>
    </li>
  </ul>
<?php end_slot(); ?>

<?php include_partial('global/graybox'); ?>