# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        my.spread.ly - home of your sharing-stats
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, my.css, font-awesome.css, openwebicons-bootstrap.css]

  javascripts:    [https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js, bootstrap.js, bootstrap-tooltip.js, bootstrap-typeahead.js, my-app.js]

  has_layout:     true
  layout:         layout
