# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  twitter:
    oauth_callback_uri: "/auth/complete_signin/service/twitter"

  facebook:
    oauth_callback_uri: "/auth/complete_signin/service/facebook"

  linkedin:
    oauth_callback_uri: "/auth/complete_signin/service/linkedin"

  google:
    oauth_callback_uri: "/auth/complete_signin/service/google"

#  delicious:
#    oauth_callback_uri: "/platform_dev.php/auth/complete_signin/service/delicious"