# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

# Production Environment
prod:
  storage:
    class: sfSessionStorage
    param:
      db_name:                 yiidit
      collection_name:         session
      session_name:            spread
      session_cookie_domain:   .spread.ly
      session_cookie_lifetime: 17776000

# Staging Environment
staging:
  storage:
    class: sfSessionStorage
    param:
      db_name:                 yiid_dev
      collection_name:         session
      session_name:            yiiddev
      session_cookie_domain:   .yiiddev.com
      session_cookie_lifetime: 17776000

# Development Environment
dev:
  storage:
    class: sfSessionStorage
    param:
      session_name:    spread_dev
      session_cookie_domain: .spread.local
      session_cookie_lifetime: 170200
      session_path: %SF_CACHE_DIR%/sessions

# Test: Testing Environment
test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false


# Default values
all:
  user:
    class: myUser