widget_like:
  url:    /like
  param:  { module: like, action: index }

widget_likes:
  url:    /likes
  param:  { module: likes, action: index }

widget_settings:
  url:    /settings
  param:  { module: settings, action: index }

widget_update_settings:
  url:    /settings/update
  param:  { module: settings, action: update }

widget_deals:
  url:    /deals/index
  param:  { module: deals, action: index }

widget_deals_example:
  url:    /deals/example
  param:  { module: deals, action: example }

widget_profile:
  url:    /profile/index
  param:  { module: profile, action: index }

get_coupon_used:
  url:    /deals/get_coupon_used
  param:  { module: deals, action: get_coupon_used }

signinto:
  url:   /auth/signinto
  param: { module: auth, action: signinto }

signin:
  url:   /signin
  param: { module: auth, action: signin }

signout:
  url:   /signout
  param: { module: auth, action: signout }

imprint:
  url:   /imprint
  param: { module: static, action: imprint }

save_like:
  url:    /like/save
  param:  { module: like, action: save }

like:
  url:   /api/like/*
  param: {module: api, action: save_like, likedis: <?php echo YiidActivityTable::ACTIVITY_VOTE_POSITIVE; ?> }

dislike:
  url:   /api/dislike/*
  param: {module: api, action: save_like, likedis: <?php echo YiidActivityTable::ACTIVITY_VOTE_NEGATIVE; ?> }

homepage:
  url:   /
  param: { module: like, action: index }

default:
  url:   /:module/:action/*