widget_like:
  url:    /like
  param:  { module: like, action: index }

widget_settings:
  url:    /settings
  param:  { module: settings, action: index }

widget_deals:
  url:    /deals
  param:  { module: deals, action: index }

widget_profile:
  url:    /profile/index
  param:  { module: profile, action: index }

signinto:
  url:   /auth/signinto
  param: { module: auth, action: signinto }

like:
  url:   /api/like/*
  param: {module: api, action: save_like, likedis: <?php echo YiidActivityTable::ACTIVITY_VOTE_POSITIVE; ?> }

dislike:
  url:   /api/dislike/*
  param: {module: api, action: save_like, likedis: <?php echo YiidActivityTable::ACTIVITY_VOTE_NEGATIVE; ?> }

homepage:
  url:   /
  param: { module: widget, action: like }

default:
  url:   /:module/:action/*