settings:
  url:    /popup/settings
  param:  { module: popup, action: settings }

# popup auth
popup_add_service:
  url:    /popup/add_service
  param:  { module: auth, action: add_service, widgetcontext: popup }

popup_signin:
  url:    /popup/signin
  param:  { module: auth, action: signin, widgetcontext: popup }

popup_confirm_signin:
  url:    /popup/confirm_signin/*
  param:  { module: auth, action: confirm_signin, widgetcontext: popup }

popup_complete_signin:
  url:    /popup/complete_signin/*
  param:  { module: auth, action: complete_signin, widgetcontext: popup }

popup_signinto:
  url:   /popup/signinto/*
  param: { module: auth, action: signinto, widgetcontext: popup }

popup_signout:
  url:    /popup/signout
  param:  { module: auth, action: signout, widgetcontext: popup }

# static auth
static_add_service:
  url:    /static/add_service
  param:  { module: auth, action: add_service, widgetcontext: static }

static_signin:
  url:    /static/signin
  param:  { module: auth, action: signin, widgetcontext: static }

static_confirm_signin:
  url:    /static/confirm_signin/*
  param:  { module: auth, action: confirm_signin, widgetcontext: static }

static_complete_signin:
  url:    /static/complete_signin/*
  param:  { module: auth, action: complete_signin, widgetcontext: static }

static_signinto:
  url:   /static/signinto/*
  param: { module: auth, action: signinto, widgetcontext: static }

static_signout:
  url:    /static/signout
  param:  { module: auth, action: signout, widgetcontext: static }
# end auth


# deal auth
deal_add_service:
  url:    /deal/add_service
  param:  { module: auth, action: add_service, widgetcontext: deal }

deal_signin:
  url:    /deal/signin
  param:  { module: auth, action: signin, widgetcontext: deal }

deal_confirm_signin:
  url:    /deal/confirm_signin/*
  param:  { module: auth, action: confirm_signin, widgetcontext: deal }

deal_complete_signin:
  url:    /deal/complete_signin/*
  param:  { module: auth, action: complete_signin, widgetcontext: v }

deal_signinto:
  url:   /deal/signinto/*
  param: { module: auth, action: signinto, widgetcontext: deal }

deal_signout:
  url:    /deal/signout
  param:  { module: auth, action: signout, widgetcontext: deal }
# end auth


load_friends:
  url:   /widget/load_friends/*
  param: {module: widget, action: load_friends }

static_like:
  url:    /static/like/*
  param:  { module: static, action: like }

like:
  url:   /api/like/*
  param: {module: api, action: save_like, likedis: <?php echo YiidActivityTable::ACTIVITY_VOTE_POSITIVE; ?> }

dislike:
  url:   /api/dislike/*
  param: {module: api, action: save_like, likedis: <?php echo YiidActivityTable::ACTIVITY_VOTE_NEGATIVE; ?> }



homepage:
  url:   /
  param: { module: widget, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*