# default rules
opendislike_stream:
  url:   /widget/stream
  param: { module: widget, action: stream }

index_generate:
  url:   /widget/generate
  param: { module: widget, action: generate }

index_index:
  url:   /widget/index
  param: { module: widget, action: generate }

index_get_dislikes:
  url:   /widget/dislikes/:page
  param: { module: widget, action: get_dislikes, page: 1 }

dislike_show:
  url:   /widget/dislike/*
  param: { module: widget, action: dislike_show }

dislike_save:
  url:   /widget/do_dislike/*
  param: { module: widget, action: dislike_save }

settings:
  url:    /popup/settings
  param:  { module: popup, action: settings }

add_service:
  url:    /popup/add_service
  param:  { module: popup, action: add_service }

signin:
  url:    /popup/signin
  param:  { module: popup, action: signin }

signout:
  url:    /popup/signout
  param:  { module: popup, action: signout }

confirm_signin:
  url:    /popup/confirm_signin/*
  param:  { module: popup, action: confirm_signin }

complete_signin:
  url:    /popup/complete_signin/*
  param:  { module: popup, action: complete_signin }

signinto:
  url:   /popup/signinto/*
  param: { module: popup, action: signinto }

like:
  url:   /api/like/*
  param: {module: api, action: like }

homepage:
  url:   /
  param: { module: widget, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
load_friends:
  url:   /widget/load_friends/*
  param: {module: widget, action: load_friends }    


