widget_like:
  url:    /
  param:  { module: like, action: index }

share:
  url:    /share
  param:  { module: like, action: nourl }

widget_like_full:
  url:    /like
  param:  { module: like, action: index }

like_get_images:
  url:    /like/get_images
  param:  { module: like, action: get_images }

widget_likes:
  url:    /likes
  param:  { module: likes, action: index }

widget_settings:
  url:    /settings
  param:  { module: settings, action: index }

widget_update_settings:
  url:    /settings/update
  param:  { module: settings, action: update }

widget_deals:
  url:    /deals
  param:  { module: deals, action: index }

widget_deals_example:
  url:    /deals/example
  param:  { module: deals, action: example }

widget_profile:
  url:    /profile
  param:  { module: profile, action: index }

nourl:
  url:    /nourl
  param:  { module: like, action: nourl }

get_like_content:
  url:    /like/get_like_content
  param:  { module: like, action: get_like_content }

get_coupon_used:
  url:    /deals/get_coupon_used
  param:  { module: deals, action: get_coupon_used }

signinto:
  url:   /auth/signinto
  param: { module: auth, action: signinto }

signin:
  url:   /signin
  param: { module: auth, action: signin }

signout:
  url:   /signout
  param: { module: auth, action: signout }

imprint:
  url:   /imprint
  param: { module: static, action: imprint }

save_like:
  url:    /like/save
  param:  { module: like, action: save }

deal:
  url:    /deal
  param:  { module: deal, action: index }

default_deal:
  url:    /deal/default
  param:  { module: deal, action: default_deal }

coupon:
  url:    /coupon
  param:  { module: deal, action: coupon }

default:
  url:   /:module/:action/*

linkwrapper:
  url:   /urlwrapper
  param:  { module: linkwrapper, action: index }