default:
  http_metas:
    content-type: text/html

  metas:
    title:        Yiid.it
    description:  Yiid helps you sharing your interesting websites
    keywords:     yiid, social, network, sharing
    #language:     en
    #robots:       index, follow

  stylesheets:    [widget/widget.css]

  javascripts:    []

  has_layout:     on
  layout:         layout