default:
  http_metas:
    content-type: text/html

  metas:
    description:  Spread.ly consists of sharing button widgets that enable users to share content into a wide range of social networks simultanously. Besides that, Spread.ly offers a sophisticated functionality to reward users for their likes.
    keywords:     sharing,sharebutton,like,likebutton,deal,dealbutton,facebook,linkedin,twitter,buzz
    #language:     en
    #robots:       index, follow

  stylesheets:    [widget/widget.css]

  javascripts:    []

  has_layout:     on
  layout:         layout