# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: landing, action: index }

stream:
  url:   /stream
  param: { module: stream, action: index }

imprint:
  url:   /imprint
  param: { module: static, action: imprint }

tos:
  url:   /tos
  param: { module: static, action: tos }

privacy:
  url:   /privacy
  param: { module: static, action: privacy }

stream_new:
  url: /stream/new
  param: { module: stream, action: new }

stream_hot:
  url: /stream/hot
  param: { module: stream, action: hot }

stream_not:
  url: /stream/not
  param: { module: stream, action: not }

get_item_detail:
  url: /stream/get_item_detail
  param: { module: stream, action: get_item_detail }

get_item_detail_stream:
  url: /stream/get_item_detail_stream
  param: { module: stream, action: get_item_detail_stream }

get_contacts_by_sortname:
  url: /stream/get_contacts_by_sortname
  param: { module: stream, action: get_contacts_by_sortname }

get_friends:
  url: /stream/get_friends
  param: { module: stream, action: get_friends }

get_active_friends:
  url: /stream/get_active_friends
  param: { module: stream, action: get_active_friends }

auth_signin:
  url:   /signin/*
  param: { module: auth, action: signin }

auth_signout:
  url:   /signout
  param: { module: auth, action: signout }

auth_complete_signin:
  url:   /auth/complete_signin/*
  param: { module: auth, action: complete_signin }

auth_basic:
  url:   /auth/basic
  param: { module: auth, action: basic }

auth_add_services:
  url:  /auth/add_services
  param: { module: auth, action: registered }

auth_add_service:
  url:  /auth/add_service/*
  param: { module: auth, action: add_service }

welcome_magic:
  url:  /magic
  param: { module: landing, action: magic }

landing:
  url: /landing
  param: { module: landing, action: index }

change_language:
  url:   /change_language
  param: { module: system, action: change_language }

update_language:
  url:   /updateLanguage/*
  param: { module: system, action: update_icon_language }

widget_callback_uri:
  url:   /popup/*
  param: { module: auth, action: widget_auth }

static:
  url:   /static/*
  param: { module: static, action: index }

wellknown:
  url:  /.well-known/host-meta
  param: { module: discovery, action: hostmeta}
  
oexchange:
  url:  /discovery/oexchange 
  param: { module: discovery, action: oexchange}  


realtime_fb:
  url:  /realtime/facebooksubscribe
  param: { module: realtime, action: subscribeFacebook }

facebookpush:
  url:  /realtime/facebookpush
  param: { module: realtime, action: facebookpush }

##### ROUTES FOR PLUGINS #######

js_log:
  url:   /general/js_log
  param: { module: general, action: js_log }

##### TEST ROUTES #######

test:
  url:   /test/index
  param: { module: test, action: index }

##
#
#  wir wollen keine default routen mehr... also alles brav eintragen ;)
#
# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*