# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: landing, action: index }

stream:
  url:   /stream
  param: { module: stream, action: index }

stream_new:
  url: /stream/new
  param: { module: stream, action: new }

stream_hot:
  url: /stream/hot
  param: { module: stream, action: hot }

stream_not:
  url: /stream/not
  param: { module: stream, action: not }

get_item_detail:
  url: /stream/get_item_detail
  param: { module: stream, action: get_item_detail }

get_item_detail_stream:
  url: /stream/get_item_detail_stream
  param: { module: stream, action: get_item_detail_stream }

get_contacts_by_sortname:
  url: /stream/get_contacts_by_sortname
  param: { module: stream, action: get_contacts_by_sortname }

get_friends:
  url: /stream/get_friends
  param: { module: stream, action: get_friends }

auth_signin:
  url:   /signin/*
  param: { module: auth, action: signin }

auth_signout:
  url:   /signout
  param: { module: auth, action: signout }

auth_complete_twitter_signin:
  url:   /auth/complete_twitter_signin
  param: { module: auth, action: complete_twitter_signin }

auth_complete_facebook_signin:
  url:   /auth/complete_facebook_signin
  param: { module: auth, action: complete_facebook_signin }

auth_basic:
  url:   /auth/basic
  param: { module: auth, action: basic }

auth_registered:
  url:  /welcome
  param: { module: auth, action: registered }

welcome_magic:
  url:  /magic
  param: { module: landing, action: magic }

landing:
  url: /landing
  param: { module: landing, action: index }

change_language:
  url:   /change_language
  param: { module: system, action: change_language }

update_language:
  url:   /updateLanguage/*
  param: { module: system, action: update_icon_language }

##### ROUTES FOR PLUGINS #######

js_log:
  url:   /general/js_log
  param: { module: general, action: js_log }

##### TEST ROUTES #######

test:
  url:   /test/index
  param: { module: test, action: index }

##
#
#  wir wollen keine default routen mehr... also alles brav eintragen ;)
#
# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*