# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  # nothing yet

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    web_debug:              true
    cache:                  false
    etag:                   false

staging:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    web_debug:              true
    cache:                  false
    etag:                   false

all:
  .actions:
    error_404_module:       static    # To be called when a 404 error is raised
    error_404_action:       404       # Or when the requested URL doesn't match any route

    login_module:           landing      # To be called when a non-authenticated user
    login_action:           index    # Tries to access a secure page

    secure_module:          landing      # To be called when a user doesn't have
    secure_action:          index    # The credentials required for an action

  .settings:
    no_script_name:         false

    # Form security secret (CSRF protection)
    csrf_secret:            16575218ebe0be6e71b177fe30a9d99711e140e4
    enabled_modules:        [general]

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    i18n:                   true
    default_culture:        de_DE

    ## load common helpers
    standard_helpers:       [Cdn, I18N, Partial]
    check_lock:             on
