# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Yiid.com
    description:  Yiid helps you sharing your interesting websites
    keywords:     yiid, social, network, sharing
    language:     en
    robots:       index, follow

  javascripts:   []

  has_layout:     true
  layout:         layout