ErrorHandler.catchGlobalError();
//jQuery('.mirror-change-value').mirrorChangeValue();
Deal.init();
DealTable.init();
DealForm.init();
Deal.showStats();
AnalyticsFilter.init();
FilterNav.init();
AnalyticsUrlFilter.init();
