#cms:
#  class: sfDoctrineRouteCollection
#  options:
#    model:                Cms
#    module:               cms
#    prefix_path:          /cms
#    column:               id
#    with_wildcard_routes: true

#cms_category:
#  class: sfDoctrineRouteCollection
#  options:
#    model:                CmsCategory
#    module:               cms_category
#    prefix_path:          /cms_category
#    column:               id
#    with_wildcard_routes: true

#trans_unit:
#  class: sfDoctrineRouteCollection
#  options:
#    model:                TransUnit
#    module:               trans_unit
#    prefix_path:          /trans_unit
#    column:               msg_id
#    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
