generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Deal
    theme:                 admin
    non_verbose_templates: false
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          deal
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        fields:
          deal_state:   { params: "disabled=true", help: "DO NOT CHANGE!!!!!!!!!!!!!!!!!!!!" }
          expire_at:    { help: "Format: YYYY-MM-DD wie z.B. 2012-12-30" }
      new:     ~