##
# Global settings
#
all:
  accepted:
    languages: [en, de]

  release_name: 'dev'

  stream:
    days_limit_hot:      30    #  days in the past we still consider as active
    days_limit_not:      30
    days_limit_new:      0     # 0 = unlimited
    days_limit_search:   30

  email:
    sender:             "the Spread.ly staff"
    address:            "noreply@spreadly.com"

  settings:
    filtered_parameters: [spreadly, yiidit, zanpid, utm_source, utm_medium, utm_campaign, utm_content, at_xt, sms_ss]  #for cleaning up urls

  image_sizes:
    avatar: ['16x16', '30x30', '48x48', '140x140']  #height x width
    community_icon: ['50x50']

  # mapper for f.e. apis
  likewidget:
    types:    ['like', 'pro', 'recommend', 'buy', 'visit', 'nice', 'rsvp']

  amazons3:
    access_key:  'AKIAJ5NSA6ET5RC4AMXQ'
    secret_key:  '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'

  twitter:
    post_api:    'http://api.twitter.com/1/statuses/update.xml'
    post_realm:  'http://twitter.com/'

  facebook:
    post_api:    'https://graph.facebook.com/me/feed'

  linkedin:
    post_api:    'http://api.linkedin.com/v1/people/~/shares'
    post_type:   'Content-Type: application/xml'
    post_realm:  'http://api.linkedin.com'

  google:
    post_api:    'https://www.googleapis.com/buzz/v1/activities/@me/@self'
    post_type:   'Content-Type: application/json'

##
# Prod settings
#
prod:
  settings:
    url:               'http://spreadly.com'
    host:              'spreadly.com'
    widgets_url:       'http://spread.ly'
    widgets_host:      'spread.ly'
    button_url:        'http://button.spread.ly'
    blog_host:         'blog.spreadly.com'
    old_platform_host: 'yiid.com'
    old_stats_host:    'yiid.it'
    document_root:     '/home/httpd/vhosts/yiid.com/httpdocs/web'
    post_to_services:  1
    environment:       'prod'
    dev:               0
    pager:             20
    gzip:              1              ## set 1 to force local gz support
    short_url:         'http://sprd.to'

  twitter:
    oauth_token:   "WbIgXrxlAbGfdpO8kLyWQ"
    oauth_secret:  "pw4tGKNa8aG4AqidMBaMpsQyDp70WSgnNVSvv9tLU"

  facebook:
    oauth_token:   "1de4ec6a73c75e7c00977bc6c9a203c4"
    oauth_secret:  "d789bd46751701a96ca3e80d8b5bff86"

  linkedin:
    oauth_token:   "tLGEinyEJmEVEzPruN8Q-MH_gLVrzTWJbc1xqbxyvTApbIxetpe89LVMyAc4nBRZ"
    oauth_secret:  "KzbTzvLkM4Yfb7Jf9_8D7QV6Vy-1IBj-XItzkmHzWFJMXNT2ZyD_KmxqM5eJ8Wnr"

  google:
    oauth_token:   "www.yiid.com"
    oauth_secret:  "bjFb+uHoYTFAQotRd5zIHkE1"

  delicious:
    oauth_token:   "dj0yJmk9V1B5N0hvd0hndkVNJmQ9WVdrOVUwOU5UVTFUTkhNbWNHbzlNakF3TmpJeU56QTFOUS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0zNQ--"
    oauth_secret:  "f77fb867c12d4620c677d4f2fe9164aed40327f7"

  check_url:     # der mac kann die checkdnsrr() methode nicht ausführen, so wird der test lokal umgangen
    pass:       0

  memcache:
    server_ip:      'bowser'

  mongodb:
    host:                 'donkeykong'
    database_name:        'yiid'
    database_name_stats:  'yiid_stats'

  amazons3:
    bucket:      'live.yiidcdn.com'
    hosts:
      - 'http://yiidstatic1.publicclubs.de'
      - 'http://yiidstatic2.publicclubs.de'

##
# Local settings
#
dev:
  settings:
    url:              'http://spreadly.local'
    host:             'spreadly.local'
    widgets_url:      'http://spread.local'
    widgets_host:     'spread.local'
    button_url:        'http://button.spread.local'
    blog_host:         'blog.spreadly.local'
    old_platform_host: 'yiid.local'
    old_stats_host:    'yiidstats.local'
    document_root:    '/Users/hschippmann/Work/symfony/yiid/web'
    post_to_services:  0
    environment:      'dev'
    dev:              1
    pager:            20
    gzip:             0              ## set 1 to force local gz support
    short_url: 'http://sprd.local'

  twitter:
    oauth_token:   "RAhMdOPsmXkm0EccGeu9w"
    oauth_secret:  "tYi4OhFRMNFbWnDZ2DEhLzOGgHidmWve9nz2qT5M3Q"

  facebook:
    oauth_token:   "4e786c7f089e38a83933c9821990030a"
    oauth_secret:  "2366aa47d946b7650fe21cf488db5694"

  linkedin:
    oauth_token:   "tLGEinyEJmEVEzPruN8Q-MH_gLVrzTWJbc1xqbxyvTApbIxetpe89LVMyAc4nBRZ"
    oauth_secret:  "KzbTzvLkM4Yfb7Jf9_8D7QV6Vy-1IBj-XItzkmHzWFJMXNT2ZyD_KmxqM5eJ8Wnr"

  google:
    oauth_token:   "www.yiid.com"
    oauth_secret:  "bjFb+uHoYTFAQotRd5zIHkE1"

  delicious:
    oauth_token:   "dj0yJmk9V1B5N0hvd0hndkVNJmQ9WVdrOVUwOU5UVTFUTkhNbWNHbzlNakF3TmpJeU56QTFOUS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0zNQ--"
    oauth_secret:  "f77fb867c12d4620c677d4f2fe9164aed40327f7"

  check_url:     # der mac kann die checkdnsrr() methode nicht ausführen, so wird der test lokal umgangen
    pass:       1

  memcache:
    server_ip:      '127.0.0.1'

  mongodb:
    host:   127.0.0.1
    database_name:  'yiid_dev'
    database_name_stats:  'yiid_stats_dev'

  amazons3:
    bucket:      'www.yiid.local'
    hosts:
      - 'http://www.yiid.local'

##
# Dev settings
#
staging:
  settings:
    url:              'http://ispread.it'
    host:             'ispread.it'
    widgets_url:      'http://yiiddev.com'
    widgets_host:     'yiiddev.com'
    button_url:        'http://button.yiiddev.com'
    blog_host:         'blog.yiiddev.com'
    old_platform_host: 'yiiddev.com'
    old_stats_host:    'stats.yiiddev.com'
    document_root:     '/home/httpd/vhosts/yiiddev.com/httpdocs/web'
    post_to_services:  1
    environment:      'staging'
    dev:              1
    pager:            20
    gzip:             1              ## set 1 to force local gz support
    short_url: 'http://sprd.ispread.it'

  twitter:
    oauth_token:   "7tHsjwbsp6pE3EnMB8MtAg"
    oauth_secret:  "xtv653ZaAsrtgVDkiGLmy6n1g061O9KRkXcYSuRpek"

  facebook:
    oauth_token:   "9fad94fc41d5129a661fad3b62406e50"
    oauth_secret:  "0b426e77c73a530a662a2cde04f4a830"

  linkedin:
    oauth_token:   "tLGEinyEJmEVEzPruN8Q-MH_gLVrzTWJbc1xqbxyvTApbIxetpe89LVMyAc4nBRZ"
    oauth_secret:  "KzbTzvLkM4Yfb7Jf9_8D7QV6Vy-1IBj-XItzkmHzWFJMXNT2ZyD_KmxqM5eJ8Wnr"

  google:
    oauth_token:   "www.yiid.com"
    oauth_secret:  "bjFb+uHoYTFAQotRd5zIHkE1"

  delicious:
    oauth_token:   "dj0yJmk9V1B5N0hvd0hndkVNJmQ9WVdrOVUwOU5UVTFUTkhNbWNHbzlNakF3TmpJeU56QTFOUS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0zNQ--"
    oauth_secret:  "f77fb867c12d4620c677d4f2fe9164aed40327f7"

  memcache:
    server_ip:      'mario'

  mongodb:
    host:                 'donkeykong'
    database_name:        'yiid_staging'
    database_name_stats:  'yiid_stats_staging'

  amazons3:
    bucket:        'dev.yiidcdn.com'
    hosts:
      - 'https://s3-eu-west-1.amazonaws.com'