autoload:
  plugin_libs:
    path:      %SF_PLUGINS_DIR%/*/lib
    recursive: true
  listener:
    path:      %SF_LIB_DIR%/listener
    recursive: true
  aws:
    path:      %SF_LIB_DIR%/utils/aws
    recursive: true
  oauth:
    path:      %SF_LIB_DIR%/vendor/OAuth
    recursive: true