##
# Prod settings
#
prod:
  translation:
    class: sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=yiidit_i18n;host=donkeykong
      username:   yiidit_i18n
      password:   fdsmolds32dfs
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8

  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=yiidit;host=donkeykong
      username:   yiidit
      password:   fdsmolds32dfs
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8

##
# Local settings
#
dev:
  translation:
    class: sfDoctrineDatabase
    param:
      dsn:        mysql:host=localhost;dbname=yiid_i18n
      username:   yiid_i18n
      password:   fdsmolds32dfs
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8

  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:        mysql:host=localhost;dbname=yiid_dev
      username:   yiid_dev
      password:   fdsmolds32dfs
      attributes:
        default_table_collate: utf8_unicode_ci
        default_table_charset: utf8

##
# Dev settings
#
staging:
  translation:
    class: sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=yiid_i18n_staging;host=donkeykong
      username:   yiid_staging
      password:   fdsmolds32dfs
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8

  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=yiid_staging;host=donkeykong
      username:   yiid_staging
      password:   fdsmolds32dfs
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8
