# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories


##
# local settings
#
dev:
  logger:
    param:
      level: debug

  mailer:
    param:
      delivery_strategy: none
      transport:
        class: Swift_NullTransport
  i18n:
    class: sfI18N
    param:
      source:               pimpedMySQL
      debug:                false
      default_culture:      de
      untranslated_prefix:  "<font color='red'>"
      untranslated_suffix:  "</font>"
      database:              mysql://yiid_i18n:fdsmolds32dfs@localhost/yiid_i18n
      cache:
        class:               sfNoCache
        param:
          lifetime:                  86400
          prefix:                    yiid_i18n
          servers:
            default:
              host: 127.0.0.1     #aws
              port: 11211
  storage:
    class: sfMongoSessionStorage
    param:
      db_table:        session
      db_id_col:       sess_id
      db_time_col:     sess_time
      db_data_col:     sess_data
      host:            localhost
      port:            27017
      db_name:         yiid_dev
      collection_name:   session
      session_name:    yiid_dev
      session_cookie_domain: .yiid.local
      session_cookie_lifetime: 17200

##
# Development settings
#
staging:
  logger:
    param:
      level: debug

  i18n:
    class: sfI18N
    param:
      source:          pimpedMySQL
      debug:           false
      default_culture: de
      database:        mysql://yiidit_i18n:fdsmolds32dfs@donkeykong/yiidit_i18n
      cache:
        class:         sfNoCache
        param:
          lifetime:                  86400
          prefix:                    yiidit_i18n
          servers:
            default:
              host: 127.0.0.1     #aws
              port: 11211

  storage:
    class: sfMongoSessionStorage
    param:
      db_table:        session
      db_id_col:       sess_id
      db_time_col:     sess_time
      db_data_col:     sess_data
      host:            donkeykong
      port:            27017
      db_name:                 yiid_staging
      collection_name:         session
      session_name:            yiid_staging
      session_cookie_domain:   .yiiddev.com
      session_cookie_lifetime: 17776000

##
# Productive settings
#
prod:
  logger:
    param:
      level: warning

  i18n:
    class: sfI18N
    param:
      source:          pimpedMySQL
      debug:           false
      default_culture: de
      database:        mysql://yiidit_i18n:fdsmolds32dfs@donkeykong/yiidit_i18n
      cache:
        class: sfFileCache
        param:
          automatic_cleaning_factor: 0
          cache_dir:                 %SF_I18N_CACHE_DIR%
          lifetime:                  86400
          prefix:                    %SF_APP_DIR%/i18n
        #class: sfMemcacheCache
        #param:
        #  lifetime:                  86400
        #  prefix:                    yiidit_i18n
        #  servers:
        #    default:
        #      host: 127.0.0.1     #aws
        #      port: 11211

  logger:
    class: sfAggregateLogger
    param:
      level: err
      loggers:
        sf_web_debug:
          class: sfWebDebugLogger
          param:
            level: debug
            condition:       %SF_WEB_DEBUG%
            xdebug_logging:  false
            web_debug_class: sfWebDebug
        sf_file_debug:
          class: sfFileLogger
          param:
            level: debug
            file: %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log

  storage:
    class: sfMongoSessionStorage
    param:
      db_table:        session
      db_id_col:       sess_id
      db_time_col:     sess_time
      db_data_col:     sess_data
      host:            donkeykong
      port:            27017
      db_name:         yiid
      collection_name:   session
      session_name:       yiid
      session_cookie_domain: .yiid.com
      session_cookie_lifetime: 17776000

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none
      transport:
        class: Swift_NullTransport

all:
  logger:
    class: sfAggregateLogger
    param:
      loggers:
        sf_web_debug:
          class: sfWebDebugLogger
          param:
            level: debug
            condition:       %SF_WEB_DEBUG%
            xdebug_logging:  false
            web_debug_class: sfWebDebug
        sf_file_debug:
          class: sfFileLogger
          param:
            level: debug
            file: %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log

  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true


  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  user:
    class: myUser
    param:
      timeout:         17776000