tinyurl:
  # for example cope#User#1
  url:   /:identifier
  param: { module: index, action: shorturl }
  
change_language:
  url:   /change_language
  param: { module: system, action: changeLanguage }

# default rules
homepage:
  url:   /
  param: { module: index, action: index }
