imprint:
  url:   /imprint
  param: { module: static, action: imprint }

tos:
  url:   /tos
  param: { module: static, action: tos }

privacy:
  url:   /privacy
  param: { module: static, action: privacy }

tinyurl:
  # for example cope#User#1
  url:   /:identifier
  param: { module: index, action: shorturl }
  
change_language:
  url:   /change_language
  param: { module: system, action: changeLanguage }

# default rules
homepage:
  url:   /
  param: { module: index, action: index }
