default:
  http_metas:
    content-type: text/html

  metas:
  #  title:        symfony project
  #  description:  symfony project
  #  keywords:     symfony, project
  #  language:     en
  #  robots:       index, follow

  has_layout:     on
  layout:         layout
  
  stylesheets: 
    - screen
    - shorturl
    - general
    - temp
  
  javascripts: [vendor/jquery-complete.min.js, vendor/prototype-complete.min.js]