generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TransUnit
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          trans_unit
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
        
      fields:
        cat_id: { label: 'Katalog' }
        source: { label: 'Wildcard' }
        target: { label: 'Übersetzung' }
      list:    
   #     actions:
   #       newWildcard: { label: new Wildcard , action: newWildcard}
        display: [cat_id, =source, target, author, updated_at]
      filter:
        display: [source, target, author, updated_at]
      form:    ~
      edit:    
        actions:
          _list:         ~
          _save:         ~
      new:
        actions:
          _list:         ~
          _save:         ~      