<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('online_identity', 'name', 'string', '255', array(
             ));
        $this->addColumn('online_identity', 'photo', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('online_identity', 'name');
        $this->removeColumn('online_identity', 'photo');
    }
}