<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('deal', 'read_only', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('deal', 'image_url', 'string', '255', array(
             ));
        $this->addColumn('deal', 'additional_tos', 'string', '255', array(
             ));
        $this->changeColumn('deal', 'type', 'enum', '255', array(
             'default' => 'commercial',
             'values' => 
             array(
              0 => 'commercial',
              1 => 'charity',
             ),
             ));
        $this->changeColumn('deal', 'coupon_type', 'enum', '255', array(
             'default' => 'single',
             'values' => 
             array(
              0 => 'single',
              1 => 'multiple',
              2 => 'url',
              3 => 'html',
             ),
             ));
        $this->changeColumn('deal', 'summary', 'string', '255', array(
             ));
        $this->changeColumn('deal', 'description', 'string', '255', array(
             ));
        $this->changeColumn('deal', 'button_wording', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('deal', 'read_only');
        $this->removeColumn('deal', 'image_url');
        $this->removeColumn('deal', 'additional_tos');
                $this->changeColumn('deal', 'type', 'enum', '10', array(
             'default' => 'commercial',
             'values' => 
             array(
              0 => 'commercial',
              1 => 'charity',
             ),
             ));
        $this->changeColumn('deal', 'coupon_type', 'enum', '10', array(
             'default' => 'single',
             'values' => 
             array(
              0 => 'single',
              1 => 'multiple',
              2 => 'url',
              3 => 'html',
             ),
             ));
        $this->changeColumn('deal', 'summary', 'string', '40', array(
             ));
        $this->changeColumn('deal', 'description', 'string', '80', array(
             ));
        $this->changeColumn('deal', 'button_wording', 'string', '35', array(
             ));
    }
}