<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('auth_token', 'token_key', 'string', '', array(
             ));
        $this->changeColumn('auth_token', 'token_secret', 'string', '', array(
             ));
        $this->changeColumn('oauth_request_token', 'token_key', 'string', '', array(
             ));
        $this->changeColumn('oauth_request_token', 'token_secret', 'string', '', array(
             ));
    }

    public function down()
    {

    }
}