<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('oauth_request_token', 'token_key', array(
             'fields' => 
             array(
              0 => 'token_key',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->addIndex('oauth_request_token', 'token_key', array(
             'fields' => 
             array(
              0 => 'token_key',
             ),
             'type' => 'unique',
             ));
    }
}