generator:
  class: sfDoctrineGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: false
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        actions:
          exportCsv:
            label: "Export to CSV"
        display: [=id, =username, email, facebook, twitter, linkedin, xing, tumblr, flattr, friend_count, like_count, share_count, first_share, last_share, created_at, updated_at]
      filter:
        display: [username, firstname, lastname, email, deal_id]
        fields:
          deal_id:
            label: "Deal ID"
      form:    ~
      edit:    ~
      new:     ~
