generator:
  class: sfDoctrineGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: false
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=id, =username, email, facebook, twitter, linkedin, friend_count, like_count, share_count, first_share, last_share]
      filter:
        display: [username, firstname, lastname, email]
      form:    ~
      edit:    ~
      new:     ~
