default:
  http_metas:
    content-type: text/html

  metas:
    title:        Yiid.it Configurator
    description:  Yiid helps you sharing your interesting websites
    keywords:     yiid, social, network, sharing
    language:     en
    robots:       index, follow

  has_layout:     on
  layout:         layout
  
  stylesheets: [configurator/configurator.css, vendor/colorpicker.css]
    
  javascripts: []
