default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  has_layout:     on
  layout:         layout
  
  stylesheets: 
    - configurator.css
    - colorpicker.css    
    
  javascripts: 
    - vendor/jquery-complete.min.js
    - vendor/colorpicker.js       
    - components/Configurator.js       