default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  has_layout:     on
  layout:         layout
  
  stylesheets: [configurator/configurator.css, vendor/colorpicker.css]
    
  javascripts: 
    - 100_main/global/100_jquery-1.4.2.min.js    
    - 100_main/global/200_jquery.form.js    
    - 100_main/vendor/colorpicker.js       
    - configurator/likebutton/Configurator.js  