default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  has_layout:     on
  layout:         layout
  
  stylesheets: [configurator/configurator.css, vendor/colorpicker.css]    