all:
  stylesheets:
  javascripts:

signinSuccess:
  components:
    content_supp: [popup, spread_description]

confirm_signinSuccess:
  components:
    content_supp: [popup, welcome_user]

settingsSuccess:
  components:
    content_supp: [popup, welcome_user]
