generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DomainProfile
    theme:                 admin
    non_verbose_templates: false
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          domain_profile
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        actions:
          exportCsv:
            label: "Export to CSV"
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      
