#Advertisement:
#  actAs:
#    Timestampable: ~

#  columns:
#    title: string(255)
#    code: string
#    domain_profile_id:
#      type:    integer
#      notnull: true
#    user_id:
#      type:    integer
#      notnull: true
#  relations:
#    DomainProfile:
#      type: one
#      local: domain_profile_id
#      foreign: id
#      foreignAlias: Advertisement
#      onDelete: CASCADE
#    sfGuardUser:
#      type: one
#      local: user_id
#      foreignAlias: Advertisement
#      onDelete: CASCADE
