options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

# new tables

AuthToken:
  actAs:
    Timestampable:  ~
  columns:
    user_id:
      type:   integer
      notnull: true
    online_identity_id:
      type:    integer
    community_id:
      type:    integer
    token_key:
      type:    string(255)
    token_secret:
      type:    string(255)
    token_type:
      type:    string(40)
    additional_params:
      type:    string
    is_publishing_enabled:
      type:    boolean
      default: false
  relations:
    User:            { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: AuthTokens }
    OnlineIdentity:  { onDelete: CASCADE, local: online_identity_id, foreign: id, foreignAlias: AuthTokens }
    Community:       { onDelete: CASCADE, local: community_id, foreign: id, foreignAlias: AuthTokens }
  indexes:
    combined_index:
      fields: [user_id, online_identity_id]
      type: unique

OauthRequestToken:
  actAs:
    Timestampable:  ~
  columns:
    token_key:
      type:    string(255)
    token_secret:
      type:    string(255)
    community_id:
      type:    integer
  relations:
    Community:       { onDelete: CASCADE, local: community_id, foreign: id, foreignAlias: OauthRequestTokens }
  indexes:
    token_key:
      fields: [token_key]
      type: unique