options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8
    
    
CmsCategory:
  actAs:
    I18n:
      fields: [title]
  columns:
    title:
      type: string(128)
    page: 
      type:  string(64)      
    footer:
      type: boolean
      default: false
      
      
Cms:
  actAs:
    I18n:
      fields: [headline, text]
  columns:
    category_id:
      type: integer
    headline:
      type:  string(128)
    text:
      type:  string(512)
    page: 
      type:  string(64)
    link:
      type: string(512)      
    active:
      type: boolean
      default: false
  relations:
    CmsCategory:        { onDelete: cascade, local: category_id, foreign: id, foreignAlias: CmsEntries }
      