detect_relations: true

Commission:
  actAs:
    Timestampable: ~

  columns:
    price: float

  # Relations
    deal_id: integer 
    domain_profile_id: integer
    ya_id: string(255)
  relations:
    Deal:
      onDelete: SET NULL
    DomainProfile:
      onDelete: SET NULL

