detect_relations: true

Deal:
  actAs:
    Timestampable: ~
    StateMachine:
      column: deal_state
      initial: initial
      states: ['initial', 'campaign_completed', 'share_completed', 'coupon_completed', 'billing_completed', 'submitted', 'active', 'inactive', 'expired']
      events:
        reset_to_campaign:
          from: ['campaign_completed', 'share_completed', 'coupon_completed', 'billing_completed']
          to: initial
        reset_to_share:
          from: ['share_completed', 'coupon_completed', 'billing_completed']
          to: campaign_completed
        reset_to_coupon:
          from: ['coupon_completed', 'billing_completed']
          to: share_completed
        reset_to_billing:
          from: ['billing_completed']
          to: coupon_completed

        complete_campaign:
          from: initial
          to: campaign_completed
        complete_share:
          from: campaign_completed
          to: share_completed
        complete_coupon:
          from: share_completed
          to: coupon_completed
        complete_billing:
          from: coupon_completed
          to: billing_completed
        submit:
          from: billing_completed
          to: submitted
        approve:
          from: submitted
          to: active
        deactivate:
          from: active
          to: inactive
        activate:
          from: inactive
          to: active
        expire:
          from: active
          to: expired

  columns:
    # Type of deal and internal name and stuff
    type:
      type: enum
      length: 255
      default: pool
      values: ['pool']
    name: string(255)
    tos_accepted:
      type: boolean
      default: false
    pool_hits:
      type: integer(4)
      default: 0

    # Conditions
    email_required:
      type: boolean
      default: false

    # Motivation stuff
    motivation_title: string(255)
    motivation_text: string

    # Share stuff
    spread_title: string(255)
    spread_text: string
    spread_url: string(255)
    spread_img: string(255)
    spread_tos: string(255)

    # Coupon stuff
    coupon_type:
      type: enum
      length: 255
      default: code
      values: ['code', 'unique_code', 'url', 'download']
    coupon_title: string(255)
    coupon_text: string
    coupon_code: string(255)
    coupon_url: string(255)
    coupon_webhook_url: string(255)
    coupon_redeem_url: string(255)

    # Billing information
    billing_type:
      type: enum
      length: 255
      default: like
      values: ['like', 'media_penetration']
    target_quantity:
      type: integer(4)
      default: 0
    actual_quantity:
      type: integer(4)
      default: 0
    price:
      type: float
    commission_pot: float
    commission_percentage: integer(4)
    commission_per_unit: float

  # Relations
    sf_guard_user_id: integer
    payment_method_id: integer
    domain_profile_id: integer
  relations:
    sfGuardUser:
      foreignAlias: Deals
      onDelete: CASCADE
    PaymentMethod:
      foreignAlias: Deals
    DomainProfile:
      foreignAlias: Deals
      onDelete: CASCADE
