detect_relations: true

Deal:
  actAs:
    Timestampable: ~
    StateMachine:
      column: deal_state
      initial: initial
      states: ['initial', 'submitted', 'approved', 'denied', 'trashed', 'paused']
      events:
        submit:
          from: ['initial', 'denied', 'approved', 'paused']
          to: submitted
        approve:
          from: ['initial', 'submitted']
          to: approved
        deny:
          from: submitted
          to: denied
        pause:
          from: approved
          to: paused
        resume:
          from: paused
          to: approved
        trash:
          from: ['submitted', 'paused', 'denied']
          to: trashed

  columns:
    # Type of deal and internal name and stuff
    type:
      type: enum
      length: 255
      default: pool
      values: ['pool']
    name: string(255)
    tos_accepted:
      type: boolean
      default: false

    # Motivation stuff
    motivation_title: string(255)
    motivation_text: string
    
    # Share stuff
    spread_title: string(255)
    spread_text: string
    spread_url: string(255)
    spread_img: string(255)
    spread_tos: string(255)
    
    # Coupon stuff
    coupon_type:
      type: enum
      length: 255
      default: code
      values: ['code', 'url', 'download']
    coupon_title: string(255)
    coupon_text: string
    coupon_code: string(255)
    coupon_url: string(255)
    coupon_redeem_url: string(255)
    
    # Billing information
    billing_type:
      type: enum
      length: 255
      default: like
      values: ['like', 'media_penetration']
    target_quantity: 
      type: integer(4)
      default: 0
    actual_quantity: 
      type: integer(4)
      default: 0
  
  # Relations
    sf_guard_user_id: integer
    payment_method_id: integer
    domain_profile_id: integer
  relations:
    sfGuardUser:
      foreignAlias: Deals
      onDelete: CASCADE
    PaymentMethod:
      foreignAlias: Deals
    DomainProfile:
      foreignAlias: Deals
      onDelete: CASCADE
