Deal:
  actAs:
    Timestampable: ~
    StateMachine:
      column: state
      initial: submitted
      states: ['submitted', 'approved', 'denied', 'trashed', 'paused']
      events:
        submit:
          from: ['denied', 'approved', 'paused']
          to: submitted
        approve:
          from: submitted
          to: approved
        deny:
          from: submitted
          to: denied
        pause:
          from: approved
          to: paused
        resume:
          from: paused
          to: approved
        trash:
          from: ['submitted', 'approved', 'paused', 'denied']
          to: trashed
          
  columns:
    domain_profile_id:
      type: integer
      notnull: true
    sf_guard_user_id:
      type: integer
      notnull: true      
    type:
      type: enum
      length: 10
      default: commercial
      values: ['commercial', 'charity']
    coupon_type:
      type: enum
      length: 10
      default: single
      values: ['single', 'multiple']
    coupon_quantity:
      type: integer
      default: 0
    coupon_current_quantity:
      type: integer
      default: 0
    start_date:
      type: datetime
    end_date:
      type: datetime
    
    summary:
      type: string(40)
    description:
      type: string(80)
    button_wording:
      type: string(35)
      
    terms_of_deal: 
      type: string(512)
    redeem_url:
      type: string(512)
    tos_accepted:
      type: boolean
      default: false 
          
  relations:
    sfGuardUser:
      foreignAlias: Deals
      onDelete: CASCADE
    DomainProfile:
      type: one
      local: domain_profile_id
      foreign: id
      foreignAlias: Deals
      onDelete: CASCADE
    Coupons:
      type: many
      local: id
      foreign: deal_id
      
Coupon:
  actAs:
    [Timestampable]
  columns:
    deal_id:
      type: integer
      notnull: true
    code:
      type: string(255)

  relations:
    Deal:
      foreignAlias: Coupons
      onDelete: CASCADE
