detect_relations: true

Deal:
  actAs:
    Timestampable: ~
    StateMachine:
      column: deal_state
      initial: initial
      states: ['initial', 'step_campaign', 'step_share', 'step_coupon', 'step_billing', 'step_verify', 'submitted', 'active', 'expired']
      events:
        edit_campaign:
          from: ['initial', 'step_campaign', 'step_share', 'step_coupon', 'step_billing', 'step_verify']
          to: step_campaign
        edit_share:
          from: ['step_campaign', 'step_share', 'step_coupon', 'step_billing', 'step_verify']
          to: step_share
        edit_coupon:
          from: ['step_share', 'step_coupon', 'step_billing', 'step_verify']
          to: step_coupon
        edit_billing:
          from: ['step_coupon', 'step_billing', 'step_verify']
          to: step_billing
        complete_edit:
          from: ['step_billing', 'step_verify']
          to: step_verify
        submit:
          from: step_verify
          to: submitted
        approve:
          from: submitted
          to: active
        expire:
          from: active
          to: expired

  columns:
    # Type of deal and internal name and stuff
    type:
      type: enum
      length: 255
      default: pool
      values: ['pool']
    name: string(255)
    tos_accepted:
      type: boolean
      default: false
    pool_hits:
      type: integer(4)
      default: 0
      
    # Conditions
    email_required:
      type: boolean
      default: false

    # Motivation stuff
    motivation_title: string(255)
    motivation_text: string
    
    # Share stuff
    spread_title: string(255)
    spread_text: string
    spread_url: string(255)
    spread_img: string(255)
    spread_tos: string(255)
    
    # Coupon stuff
    coupon_type:
      type: enum
      length: 255
      default: code
      values: ['code', 'url', 'download']
    coupon_title: string(255)
    coupon_text: string
    coupon_code: string(255)
    coupon_url: string(255)
    coupon_redeem_url: string(255)
    
    # Billing information
    billing_type:
      type: enum
      length: 255
      default: like
      values: ['like', 'media_penetration']
    target_quantity: 
      type: integer(4)
      default: 0
    actual_quantity: 
      type: integer(4)
      default: 0
  
  # Relations
    sf_guard_user_id: integer
    payment_method_id: integer
    domain_profile_id: integer
  relations:
    sfGuardUser:
      foreignAlias: Deals
      onDelete: CASCADE
    PaymentMethod:
      foreignAlias: Deals
    DomainProfile:
      foreignAlias: Deals
      onDelete: CASCADE
