Deal:
  actAs:
    Timestampable: ~
    StateMachine:
      column: deal_state
      initial: initial
      states: ['initial', 'submitted', 'approved', 'denied', 'trashed', 'paused']
      events:
        submit:
          from: ['initial', 'denied', 'approved', 'paused']
          to: submitted
        approve:
          from: ['initial', 'submitted']
          to: approved
        deny:
          from: submitted
          to: denied
        pause:
          from: approved
          to: paused
        resume:
          from: paused
          to: approved
        trash:
          from: ['submitted', 'paused', 'denied']
          to: trashed

  columns:
    domain_profile_id:
      type: integer
      notnull: true
    sf_guard_user_id:
      type: integer
      notnull: true
    type:
      type: enum
      length: 255
      default: commercial
      values: ['commercial', 'charity']
    coupon_type:
      type: enum
      length: 255
      default: single
      values: ['single', 'multiple', 'url', 'html']
    coupon_quantity:
      type: integer
      default: 0
    coupon_claimed_quantity:
      type: integer
      default: 0
    tags:
      type: string(512)
      default: null
    start_date:
      type: timestamp
    end_date:
      type: timestamp

    # a short summary
    summary:
      type: string(255)
    # the deal description
    description:
      type: string(255)
    # a comment for the facebook stream
    comment:
      type: string(255)
    # the text behind the button
    button_wording:
      type: string(255)

    terms_of_deal:
      type: string(512)
    redeem_url:
      type: string(512)
    tos_accepted:
      type: boolean
      default: false
    read_only:
      type: boolean
      default: false
    image_url:
      type: string(255)
    additional_tos:
      type: string(255)

  relations:
    sfGuardUser:
      foreignAlias: Deals
      onDelete: CASCADE
    DomainProfile:
      type: one
      local: domain_profile_id
      foreign: id
      foreignAlias: Deals
      onDelete: CASCADE
    Coupons:
      type: many
      local: id
      foreign: deal_id

Coupon:
  actAs:
    [Timestampable]
  columns:
    deal_id:
      type: integer
      notnull: true
    code:
      type: text

  relations:
    Deal:
      foreignAlias: Coupons
      onDelete: CASCADE
