options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8
      
Language:
  columns:
    lang: 
      type:  string(5)
      notnull: true
    default_lang:   
      type: boolean
      notnull: true
      default: false 
    is_active:      
      type: boolean
      notnull: true
      default: false
  indexes:
    language_uniq:
      fields:  [lang]
      type:    unique
    is_active:
      fields:  [is_active]
    
Catalogue:      
  actAs:
    Timestampable:  ~
  columns:
    name: 
      type: string(100)
      notnull: true
    source_lang:
      type: string(10), required: true,  default: '' }
    target_lang: 
      type:   string(100)
      notnull: true,  
      default: ''
    author:       
      type: string(255)
     
  relations:    
    Language:     { onDelete: CASCADE, local: target_lang, foreign: lang, foreignAlias: Catalogues }
  indexes:
    name:
      fields:  [name]
      
TransUnit:      
  actAs:
    Timestampable:  ~
  columns:
    msg_id:
      type: integer
      notnull: true
    cat_id: 
      type: integer
      notnull: true
      default: 1    
    id:           
      type: string(255)
      notnull: true
      default: '' 
    source:       
      type: string
      notnull: true
    target:
      type: string 
      notnull: true  
    comments:   
      type: string
    author:       
      type: string(255)
    translated:   
      type: boolean
      default: false 
  relations:    
    Catalogue:     { onDelete: CASCADE, local: cat_id, foreign: id, foreignAlias: Transaltions }