options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8
      
Language:
  connection:  translation
  actAs:
    Timestampable:  ~
  columns:
    lang: 
      type:  string(5)
      notnull: true
    default_lang:   
      type: boolean
      notnull: true
      default: false 
    is_active:      
      type: boolean
      notnull: true
      default: false

  indexes:
    language_uniq:
      fields:  [lang]
      type:    unique
    is_active:
      fields:  [is_active]
    
Catalogue:      
  connection:  translation
  columns:
    cat_id:
      autoincrement: true
      primary:  true
      type:  integer
    name: 
      type: string(100)
      notnull: true
    source_lang:
      type: string(10), required: true,  default: '' }
    target_lang: 
      type:   string(100)
      notnull: true,  
      default: ''
    author:       
      type: string(255)
    date_created:
      type: integer
    date_modified: 
      type: integer
  relations:    
    Language:     { onDelete: CASCADE, local: target_lang, foreign: lang, foreignAlias: Catalogues }
  indexes:
    name:
      fields:  [name]
      
TransUnit:      
  connection:  translation
  actAs:
    Timestampable:  ~
  columns:
    msg_id:
      type: integer
      autoincrement: true
      primary:  true
    cat_id: 
      type: integer
      notnull: true
    source:       
      type: string
      notnull: true
    target:
      type: string 
      notnull: true  
    comments:   
      type: string
    author:       
      type: string(255)
    translated:   
      type: boolean
      default: false 
    date_added:
      type: integer
    date_modified:
      type: integer
  relations:    
    Catalogue:     { onDelete: CASCADE, local: cat_id, foreign: cat_id, foreignAlias: Translations }