options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8
      
Language:
  connection:  translation
  actAs:
    Timestampable:  ~
  columns:
    lang: 
      type:  string(5)
      notnull: true
    default_lang:   
      type: boolean
      notnull: true
      default: false 
    is_active:      
      type: boolean
      notnull: true
      default: false

  indexes:
    language_uniq:
      fields:  [lang]
      type:    unique
    is_active:
      fields:  [is_active]




Catalogue:
  connection:  translation
  columns:
    cat_id: { type: integer, notnull: true, autoincrement: true, primary: true }
    name: { type: string(100), notnull: true, default: '' }
    source_lang: { type: string(100), notnull: true, default: '' }
    target_lang: { type: string(100), notnull: true, default: '' }
    date_created: { type: integer, notnull: true, default: 0 }
    date_modified: { type: integer, notnull: true, default: 0 }
    author: { type: string(255), notnull: true, default: '' }
    
TransUnit:
  connection:  translation
  actAs:
    Timestampable:  ~
  columns:
    id: { type: integer, notnull: true, autoincrement: true, primary: true }
    cat_id: { type: integer, notnull: true}
    source: { type: clob(65532), notnull: true }
    target: { type: clob(65532), notnull: true }
    author: { type: string(255), notnull: true, default: ''}
    translated: { type: boolean, notnull: true, default: false }    
  relations:
    Catalogue:
      local: cat_id
      foreign: cat_id
      foreignAlias: Units      