options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

OnlineIdentity:
  actAs:
    MemcacheBehavior: ~
    Timestampable:  ~
  columns:
    community_id:
      type: integer
      notnull: true
    user_id:
      type: integer
    title:
      type:     string(120)
    name:
      type:     string(255)
    photo:
      type:     string(255)
    identifier:
      type:     string(255)
    identity_type:
      type:     integer(4)
    feed_identifier:
      type:     string(120)
    auth_identifier:
      type:     string(255)
    auth_identity_type:
      type:     integer(4)
    social_publishing_enabled:
      type:       boolean
      default:    false
  relations:
    Community: { onDelete: CASCADE, local: community_id, foreign: id, foreignAlias: OnlineIdentitys }
  indexes:
    auth_identifier:
      fields: [auth_identifier]
      type:   unique
    combined_index:
      fields: [community_id, identifier, identity_type]
      type:   unique


OnlineIdentityCon:
  actAs:
    Timestampable:  ~
  columns:
    from_id:
      type:       integer
      notnull:    true
    to_id:
      type:       integer
      notnull:    true
  relations:
    OnlineIdentityFrom:   { class: OnlineIdentity, onDelete: CASCADE, local: from_id, foreign: id, foreignAlias: OnlineIdentitysFrom }
    OnlineIdentityTo:     { class: OnlineIdentity, onDelete: CASCADE, local: to_id, foreign: id, foreignAlias: OnlineIdentitysTo }
  indexes:
    combined_index:
      fields: [from_id, to_id]
      type:   unique