options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

OnlineIdentity:
  actAs:
    MemcacheBehavior: ~
    Timestampable:  ~     
  columns:
    community_id:
      type: integer
      notnull: true    
    title:
      type:     string(120)
    identifier:
      type:     string(255)
    identity_type: 
      type:     integer(4)
    feed_identifier:
      type:     string(120)
    auth_identifier:
      type:     string(255)
    auth_identity_type:
      type:     integer(4)
    social_publishing_enabled:
      type:       boolean
      default:    false    
  relations:
    Community: { onDelete: CASCADE, local: community_id, foreign: id, foreignAlias: OnlineIdentitys }   
  indexes:
    auth_identifier:
      fields: [auth_identifier]
      type:   unique  
    combined_index:  
      fields: [community_id, identifier, identity_type]
      type:   unique
