options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

OnlineIdentity:
  actAs:
    NoMemcacheBehavior: ~
    Timestampable:  ~
  columns:
    community_id:
      type:     integer
      notnull:  true
    user_id:
      type:     integer
      notnull:  false
    original_id:
      type:     string(16)
    title:
      type:     string(120)
    name:
      type:     string(255)
    photo:
      type:     string(255)
    identifier:
      type:     string(255)
    profile_uri:
      type:     string(255)
    gender:
      type:     string(1)
    birthdate:
      type:     date
    relationship_state:
      type:     integer(4)
      default:  0
    location_raw:
      type:     string(255)
    auth_identifier:
      type:     string(255)
    auth_identity_type:
      type:     integer(4)
    social_publishing_enabled:
      type:       integer(4)
      default:    0
    friend_ids:
      type:     text
    friend_count:
      type:     integer(4)
      default:  0
    last_friend_refresh:
      type:     integer
      default:  0
  relations:
    Community: { onDelete: CASCADE, local: community_id, foreign: id, foreignAlias: OnlineIdentitys }
    User:      { onDelete: SET NULL, local: user_id, foreign: id, foreignAlias: OnlineIdentitys }
  indexes:
    auth_identifier:
      fields: [auth_identifier]
      type:   unique
    combined_index:
      fields: [community_id, original_id]
      type:   unique