options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

ShortUrl:
  actAs:
    Timestampable:  ~

  columns:
    url:
      type:    string(512)
    ip:
      type:    string(25)
  indexes:
    url_prefix:
      fields: [url(45)]