options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

SocialObject:
  columns:
    id:
      type:  string(24)
    url:
      type:  string
    url_hash:
      type:  string(32)
    alias:
      type:  string
    oiids:     ## onlineIdentitys which participated on this object
      type:  string
    cids:      ## CommunityIds where this object was shared in
      type:  string
    type:
      type:  integer(4)
    title:
      type:  string(255)
    stmt:      ## description
      type:  string
    ecode:
      type:  string
    thumb_url:
      type:  string
    l_cnt:
      type:  integer
      default: 0
    d_cnt:
      type:  integer
      default: 0
    c_cnt:
      type:  integer
      default: 0
    u:
      type:  integer
    c:
      type:  integer

YiidActivity:
  columns:
    id:
      type:      string(24)
    so_id:
      type:      string(24)
    url:
      type:      string
    url_hash:
      type:      string(32)
    u_id:
      type:      integer
    oiids:
      type:      string
    cids:        # community id
      type:      integer
    score:
      type:      integer(4)
    verb:
      type:      integer(4)
    c:
      type:      integer

### indices mmüssen noch definiert werden
# db.social_object.ensureIndex({url: 1}, { unique: true });
# db.social_object.ensureIndex({alias: 1}, { unique: true });
# db.yiid_activity.ensureIndex({so_id: 1, u_id: 1}, { unique: true });
# db.session.ensureIndex({sess_id: 1}, { unique: true });

### neu
#
#  index auf oiids
#  index auf cids
#
#