options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

SocialObject:
  columns:
    id:
      type:  string(30)
    url:
      type:  string
    url_hash:
      type:  string(32)
    alias:
      type:  string
    oiids:     ## onlineIdentitys which participated on this object
      type:  string
    cids:      ## CommunityIds where this object was shared in
      type:  string
    uids:      ## all involved user ids
      type:  string
    type:
      type:  integer(4)
    title:
      type:  string(255)
    stmt:      ## description
      type:  string
    ecode:
      type:  string
    thumb_url:
      type:  string
    l_cnt:
      type:  integer
      default: 0
    d_cnt:
      type:  integer
      default: 0
    c_cnt:
      type:  integer
      default: 0
    enriched:
      type: integer
      default: 0
    u:
      type:  integer
    c:
      type:  integer

YiidActivity:
  columns:
    id:
      type:      string(30)
    so_id:
      type:      string(24)
    url:
      type:      string
    url_hash:
      type:      string(32)
    u_id:
      type:      integer
    oiids:
      type:      string
    cids:        # community id
      type:      string
    score:
      type:      integer(4)
    verb:
      type:      integer(4)
    # <clickback>
    cb_referer:
      type:      string(30)
    cb_service:
      type:      string(30)
    clickback:
      type:      string(255)
    # </clickback>
    # <deal>
    d_id:        # deal id
      type:      integer(4)
    c_code:      # coupon code
      type:      string(255)
    # </deal>
    c:
      type:      integer
    tags:        # array with used tags
      type:      string
    title:
      type:      string(255)
    descr:
      type:      string(255)
    thumb:
      type:      string(255)
    comment:
      type:      string

SocialAdvertisement:
  actAs:
    Timestampable: ~
    I18n:
      fields: [title, description]
  columns:
    title:
      type: string(40)
    description:
      type: string(255)
    url:
      type: string(255)
    so_id:
      type: string(40)
    is_active:
      type: boolean
      default: false