DomainProfile:
  actAs: [Timestampable]
  columns:
    url:
      type: string(255)
    protocol:
      type: enum
      length: 5
      default: http
      values: ['http', 'https']
    state:
      type: enum
      length: 10
      default: pending
      values: ['pending', 'verified']
    verification_token:
      type: string(255)
      unique: true
    verification_count:
      type: integer
      default: 0
    sf_guard_user_id:
      type: integer
      notnull: true
    imprint_url:
      type: string(512)
    tos_url:
      type: string(512)
    
  relations:
    sfGuardUser:
      foreignAlias: DomainProfiles
      onDelete:     CASCADE
    Deals:
      class: Deal
      type: many
      local: id
      foreign: domain_profile_id
      onDelete: CASCADE

SupportedServices:
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
    slug:
      type: string(255)
    url:
      type: string(255)
    tutorial_url:
      type: string(255)
    download_url:
      type: string(255)

      
Visit:
  columns:
    host:     { type: string(255) }
    uri:      { type: string  }
    cult:     { type: string(5) }
    is_like:     { type: boolean, default: false }
    is_dislike:  { type: boolean, default: false }
    c:        { type: integer }
    