options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

User:
  actAs:
    NoMemcacheBehavior: ~
    Timestampable:  ~
  columns:
    username:
      type:       string(63)
      unique:     true
    passwordhash:
      type:       string(32)
    salt:
      type:       string(8)
    gender:
      type:       string(1)
    description:
      type:       string
    salutation:
      type:       string(32)
    title:
      type:       string(64)
    firstname:
      type:       string(64)
    lastname:
      type:       string(64)
    sortname:
      type:       string(128)
      default:    ''
      notnull:    true
    birthdate:
      type:       date
    relationship_state:
      type:       integer(4)
      default:    0
    culture:
      type:       string(7)
    email:
      type:       varchar(120)
      notnull:    false
    agb:
      type:       boolean
      default:    false
    ip:
      type:       string(128)
    active:
      type:       boolean
      notnull:    true
      default:    false
    default_avatar:
      type:       string(50)
    credentials:
      type:       string(30)
    credcommunities:
      type:       string(100)
    done:
      type:       integer
      default:    0
      notnull:    true
    last_activity:
      type:       integer
      default:    0
    # temp fields
    is_first_login:
      type:       boolean
      default:    true